### ISSUE TITLE
Improve docs regarding modality and the usage of different metadata files

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#1001]
**Is your feature request related to a problem? Please describe.**
Let's get a clear explanation of when each metadata file will be present for each modality. (when is there acquisition/instrument and when is there rig/session).

**Describe the solution you'd like**
Build a resource that describes the distinctions between modalities and what files are used when

**Comment by saskiad** [comment]
Can you explain what isn't clear in the read the docs?

**Comment by jtyoung84** [comment]
Already in the readthedocs page
