### ISSUE TITLE
Enforce default formatting

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-data-schema#1043]
Testing out auto-enforcing default= and ellipsis formatting in pydantic classes

**Comment by dbirman** [comment]
This mostly works it catches situations where default= is missing and ... are missing, e.g. if you define name: type = Field(). But it also is incorrectly flagging situations where you define name: type = Field(value) which it should ignore. Tbd if it's worth fixing and making a PR

**Comment by bruno-f-cruz** [comment]
Related to #770
