### ISSUE TITLE
Default external_links value incorrect

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-data-schema#1044]
**Describe the bug**
The default value for Metadata.external_links is incorrect. It should be an optional dictionary instead of empty list.

**To Reproduce**
1. Go to 'external_links` definition [here](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/687b7a3c4aa55552c89a80a3e6634a6c84f022fa/src/aind_data_schema/core/metadata.py#L83C4-L85C6)
2. Observe incorrect default
3. Alternatively, try to create a Metadata instance and observe pydantic warnings for external_links value.

**Expected behavior**
External_links default should match the type (optional dictionary instead of empty list)

**Additional context**

**Comment by jtyoung84** [comment]
It looks like it's duplicated here: https://github.com/AllenNeuralDynamics/aind-data-schema/issues/1044

**Comment by jtyoung84** [comment]
Since there's a small discussion on the other ticket already, I'm going to close this one out.
