### ISSUE TITLE
Brain atlas model for targeted structures

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#1057]
**Is your feature request related to a problem? Please describe.**
Brain atlas has been added to the models, let's use it in the schema.

**Describe the solution you'd like**
Use the brain atlas model for targeted structures. In many places in procedures and session

**Describe alternatives you've considered**

**Additional context**

**Comment by dbirman** [comment]
If we update aind-data-schema-models to have enum classes based on Bruno's PR then this should wait on that
