### ISSUE TITLE
Create enum list from existing json

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#108]
** FOR JANUARY** 

**Describe the solution you'd like**
when constructing the session json, have the enum for fields (e.g.) probe name come from the rig json for the rig being used.

**Comment by mekhlakapoor** [comment]
@saskiad Can I add this back to the project board? or shall we close this ticket?

**Comment by mekhlakapoor** [comment]
@saskiad is this still an issue?

**Comment by mekhlakapoor** [comment]
Closing this issue as stale
