### ISSUE TITLE
Simplify stream modules

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#1097]
**Is your feature request related to a problem? Please describe.**
Can  ephys_modules fiber_modules and manipulator_modules be combined into one field?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saskiad** [comment]
@mekhlakapoor we discussed this last week, correct? Can we close this ticket?

**Comment by mekhlakapoor** [comment]
The different modules were separated for users. Closing this issue as not planned
