### ISSUE TITLE
Schema version field prevents validating older versioned data

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-data-schema#1099]
# User story
As a user I want to to be able to validate models when the underlying data is valid. I can't do this because old data (which might be valid under the current schema) will always fail to validate because of the `schema_version` field. 

Would be great to get a solution built into the schema for this, possibly annotating the version field with https://docs.pydantic.dev/2.0/api/functional_validators/#pydantic.functional_validators.SkipValidation

# Acceptance criteria
- [ ] An old metadata.json with version 1.0.0 (for example) should validate against aind-data-schema 1.1.0, etc.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
Removing the field doesn't work because it's required

**Comment by dbirman** [comment]
Actually it's impossible to validate even with the field removed, I think it has to get explicitly set to the correct value, I guess pulled from the main schema maybe?

**Comment by bruno-f-cruz** [comment]
Check here for a possible solution: 
Implementation: https://github.com/AllenNeuralDynamics/Aind.Behavior.Services/blob/9629b92a08878c8adf3b58de3240017dc43196b9/src/DataSchemas/aind_behavior_services/session/__init__.py#L27

Test:
https://github.com/AllenNeuralDynamics/Aind.Behavior.Services/blob/main/tests/test_schema_version_coercion.py

The strategy is to assume that the only incompatibility is a field that is coercable. The value will be updated and the rest of the schema runs as is. If it crashes one assumes it is not compatible if it doesn't we assume it is. Once deserialized without throwing, you assume that the deserialized object is from the latest library version.
