### ISSUE TITLE
Clarify library versioning scheme

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#1103]
**Is your feature request related to a problem? Please describe.**

The current repository states that the library is following semver:
>Be aware that this package is still under heavy preliminary development. Expect breaking changes regularly, although we will communicate these through semantic versioning.

However, the most recent release broke the 1.x version. Specifically, I believe that the following two PRs are not backward compatible:
#1035 
#1074 

**Describe the solution you'd like**
I do understand that strictly following semver will likely be very hard given the goal of this library. However, I still think that from both a dev and user point of view, releases must be more transparent regarding breaking changes. Therefore I ask that, similarly to other libraries [like pydantic](https://github.com/pydantic/pydantic/releases/tag/v2.9.0), to explicitly tag the breaking changes in the release notes (or even keep a changelog).

**Describe alternatives you've considered**
Strictly follow semver and bump the major release on breaking changes.

**Additional context**

**Comment by dbirman** [comment]
@bruno-f-cruz can you describe the issues you're having with #1074? This should not have broken anything -- nobody should have been using the 1.0.0 qc schema, it was a mistake that it was included at all in that release.

**Comment by bruno-f-cruz** [comment]
Sorry, let me clarify. 

I noticed this when looking at a diff of some automatically generated code I ran on v1.1.0 vs v1.0.0 (but one can also look at the [json-schemas generated by the repo](https://github.com/AllenNeuralDynamics/aind-data-schema/compare/v1.0.0...v1.1.0#diff-e0e5d3c059e2faf587bcd1bb038fd55e587468fd7da5977842f9457f69e53befL15381-R15020)). The first discrepancy I saw was actually from #1035 where a previous nullable and optional value is now longer such. 
After noticing it, I went through the PRs of the release and realized that #1074 also breaks backward compatibility. 

The present issue is not concerned with how the concrete implementation broke (or even if someone noticed it) the library. All I am pointing out is that this information should be made more transparent to users and developers, especially because it violates the promise made in the readme of the repository.

**Comment by dbirman** [comment]
The intention is to release versions as described by semver. Occasionally there are going to be mistakes, e.g. #1035 should have been merged into the v2 branch and not into dev. I think in this case the mistake is minor and not worth the effort of reverting.

I'm going to close this issue, n the future we'll need to be more careful about which branch PRs are merging into. Re-open this as a discussion if there's more to discuss, thanks.

**Comment by dbirman** [comment]
Actually @bruno-f-cruz what I think makes sense here is to open a ticket to change the tests to use real examples, which I think will help resolve this since part of the issue here is that the use of model_construct in the tests hides these kind of breaking changes when we make upgrades to the schema. 

I'll take care of opening that ticket, but it will take time to make those changes.
