### ISSUE TITLE
new sensor type for janelia lick detector

### ISSUE THREAD

**Issue by alakunina** [AllenNeuralDynamics/aind-data-schema#1199]
Could "conductive" be added as a lick sensor type? To describe the janelia lick sensor, which detects a completed circuit when the tongue touches the lick spout, e.g. using the mouse as a switch. Open to other suggestions on how to describe this type of sensor.

**Comment by saskiad** [comment]
I can add this, but isn't this the same as capacitive?

**Comment by alakunina** [comment]
![image](https://github.com/user-attachments/assets/2ba879aa-0e13-4139-a566-df4f7080707b)

@galenlynch created this diagram illustrating the difference. Top is lickety split, bottom is Janelia sensor. The lickety split detects changes in capacitive load when the mouse licks the metal tube and thus draws voltage from it. The Janelia sensor detects current flowing through the mouse when the mouse licks the tube and completes the circuit.
