### ISSUE TITLE
Changes to Imaging Acquisition schema

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#129]
Some suggested changes and questions to the acquisition schema (up for discussion) are as follows:

CHANGES
* Add _unit to end of any field name that has tangible units associated with it.
* Remove voxel_size from Axis() and fold it into Tile().
* Remove step_size_z from Acquisition() and fold it into Tile().
* Change tile_overlap from percent to microns.
* Remove enabled field from Channel (not needed). Implicitly enabled if it is listed as a channel.
* Remove the tile_prefix since I think this won't be needed (see below).
* We restructure positions and channels within a tiles class. 
* Nest Position, Channel, DAQ, Notes --> within Tile.
     * Tiles
└── Filename
└── Voxel size --> this contains voxel_size_x_um, voxel_size_y_um, voxel_size_z_um
└── Position
└── Channel
└── DAQ
└── Notes
     * Add a field for filename string which will point to the datafile name corresponding to this tile.
     * Rename positions to position, and make change to Position instead of List[Position]
     * Rename channels to channel, and make change to Channel instead of List[Channel]
     * Rename daqs to daq, and make change to dict instead of List[dict]
     
QUESTIONS
* Do we coordinate the Axis name with the instrument schema? In the instrument schema we have stage_axis_direction which is instrument specific. Also stage_axis_name which maps to the lettered axis of the system's stage. Within our acquisition software we remap stage_axis_name to what is essentially acquisition_axis_names. Acquisition_axis_names maps to stage_axis_direction but for readability and verbose reasons, we do not use the terms "detection axis", "illumination axis", and "perpendicular axis" but instead "Z", "X", and "Y" respectively. So the mapping goes something like X --> Z, Y --> Z, Z --> Y. How should we handle this in the acquisition schema Axis class?
* Consider removing additional parameters, seems overlapping with notes?
* Consider removing tile overlap from Acquisition(). It is captured more indirectly in the position of each tile. Unless it is handy to be able to quickly know how much overlap was used in the dataset?
* Consider removing volume from Axis(). Same as above, unless at quick glance it is useful to know how large the overall dataset volume is?
Example envisioned code below...
```python
""" example ExaSPIM acquisition """
from aind_data_schema.imaging import acquisition

acq=acquisition.Acquisition(
    experimenter_full_name="###", # TODO. need to add this to the GUI/config
    subject_id="###", # TODO. need to grab this from the config
    instrument_id="###", # TODO. is this needed?
    session_start_time="###", # TODO. fill this field at start of record function
    session_end_time="###", # TODO.fill this field at end of record function
    local_storage_directory="D:", # TODO. grab this from config 
    external_storage_directory="Z:", # TODO. grab this from config 
    axes=[
        acquisition.Axis(
            name="X", # Tiger motor axis. Do we coordinate this with the conventions in the instrument schema?
            dimension=2, # Imaris file axis dimension -> informed by sample pose remapping
            direction="Left_to_right", # TODO. Think about how we capture this.
        ),
        acquisition.Axis(
            name="Y", # Tiger motor axis. Do we coordinate this with the conventions in the instrument schema?
            dimension=1, # Imaris file axis dimension -> informed by sample pose remapping
            direction="Anterior_to_posterior", # TODO. Think about how we capture this.
        ),
        acquisition.Axis(
            name="Z", # Tiger motor axis. Do we coordinate this with the conventions in the instrument schema?
            dimension=0, # Imaris file axis dimension -> informed by sample pose remapping
            direction="Inferior_to_superior", # TODO. Think about how we capture this.
        )
    ]
    tiles=[
        acquisition.Tile(
            filename="tile_X_0000_Y_0000_Z_0000_CH_488.ims", # TODO. grab this from config.
            voxel_size=[
                voxel_size_x_um=0.748, # TODO. grab this from config.
                voxel_size_y_um=0.748 # TODO. grab this from config.
                voxel_size_z_um=1.000 # TODO. grab this from config.
            ],
            position=acquisition.Position(
                x_start_um=0, # TODO. grab this from config.
                x_end_um=100, # TODO. grab this from config.
                y_start_um=0, # TODO. grab this from config.
                y_end_um=100, # TODO. grab this from config.
                z_start_um=0, # TODO. grab this from config.
                z_end_um=100 # TODO. grab this from config.
            ),
            channel=acquisition.Channel(
                channel=488, # TODO. grab this from config.
                laser_power=200, # TODO. grab this from config.
                filter_wheel_index=0 # TODO. grab this from config.
            ),
            daq=[
                etl_buffer_time_ms=5.0, # TODO. grab this from config.
                etl_amplitude_volt=0.2, # TODO. grab this from config.
                etl_offest_volt=1.77 # TODO. grab this from config.
            ],
            notes="these are my notes"
        ),
        acquisition.Tile(
            filename="tile_X_0000_Y_0000_Z_0000_CH_561.ims",
            voxel_size=[
                voxel_size_x_um=0.748, # TODO. grab this from config.
                voxel_size_y_um=0.748 # TODO. grab this from config.
                voxel_size_z_um=1.000 # TODO. grab this from config.
            ],
            position=acquisition.Position(
                x_start_um=0, # TODO. grab this from config.
                x_end_um=100, # TODO. grab this from config.
                y_start_um=0, # TODO. grab this from config.
                y_end_um=100, # TODO. grab this from config.
                z_start_um=0, # TODO. grab this from config.
                z_end_um=100 # TODO. grab this from config.
            ),
            channel=acquisition.Channel(
                channel=561, # TODO. grab this from config.
                laser_power=200, # TODO. grab this from config.
                filter_wheel_index=0 # TODO. grab this from config.
            ),
            daq=[
                etl_buffer_time_ms=5.0, # TODO. grab this from config.
                etl_amplitude_volt=0.2, # TODO. grab this from config.
                etl_offest_volt=1.77 # TODO. grab this from config.
            ],
            notes="these are my notes"
        ),
    ]
)

inst.write_standard_file(prefix="exaspim_acquisition")
```

**Comment by miketaormina** [comment]
A few additional thoughts:
1. Do we need a `class ImmersionMedia()`? It doesn't properly belong to instrument or specimen and I think there a few good reasons to track it in the acquisition schema.
2. How should something like instrument calibration fit in to all of this? There are unfortunately too many use cases to stay coherent, but the relevant thing for SmartSPIM would be laser power at the excitation objective.

Elaborating on point number 2, the operator is presented with (for each channel) a slider bar for left and right side excitation that is a percentage of maximum power. The laser power that actually makes it this far depends on alignment and age of a laser and can vary over short time scales, so the only sensible way to populate `acquisition.Channel()` is to have the operator take a measurement for each laser on each side before loading in a sample chamber and then to have the percentage of an acquisition translate into mW for the schema.

Another device that I can foresee needing something like this are the AOTFs that @adamkglaser may use on the exaSPIMs. These typically have tuning curves that need to be validated periodically in order to get the best transmission of any given wavelength.

**Comment by dyf** [comment]
Couple comments @miketaormina @adamkglaser 

1. re: immersion media in ophys on the rig. we could revisit that, or do the same here. https://github.com/AllenNeuralDynamics/aind-data-schema/blob/7e38395e6e99f9c14d8a849ab41fb718a9143d6f/src/aind_data_schema/ophys/ophys_rig.py#L63
2. re: calibration data. this is tricky. let's discuss.
3. re: units at the end of field names. I'm not a fan of this. The units are defined in the schema, but I agree it is hard to find.
4. re: instrument ID - yeah we need this to link it to the instrument definition.
5. re: axis names - I think acquisition X/Y/Z should be consistent with instrument X/Y/Z if possible. If not, people will get super confused. But this nicely demonstrates why the terms X/Y/Z are ambiguous :).
