### ISSUE TITLE
Validator for "Other"

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#169]
When people select Other from an Enum, they need to provide the information in the Notes. Can we have a validator that forces this?

**Comment by dyf** [comment]
In Pydantic this is easy. The GUI will need investigating.

**Comment by Sun-flow** [comment]
I haven't done a Validator yet, can someone elaborate on what this is or provide an example? @dyf @saskiad

**Comment by saskiad** [comment]
I haven't made one myself, but they are functions within the schema that create/enforce rules in the schema. There's an example in ephys_rig https://github.com/AllenNeuralDynamics/aind-data-schema/blob/6e23ae05eadddd639baf7913857e6b41c57d7bfd/src/aind_data_schema/ephys/ephys_rig.py#L187

Probably worth looking at some pydantic documentation on validators

**Comment by Sun-flow** [comment]
Locations I have found that contain reference to `enum.OTHER` and contain a `notes` field: `procedures.SpecimenProcedure`, `processing.DataProcess`, `session.RewardDelivery`, `behavior_session.RewardDelivery`, `instrument.Instrument`, `mri_session.MRIScan`,
