### ISSUE TITLE
Cage ID

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#172]
Add Cage ID to subject schema to indicate social housing

**Comment by dyf** [comment]
Call it `housing_group`? 

https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C90394

**Comment by saskiad** [comment]
not sure... I'd prefer to be precise. But we need to see what this looks like in Labtacks. Can the same cage ID be used for different mice at different times. Eg. is the cage number a rack position?

**Comment by saskiad** [comment]
one approach is to have a housing class that contains an identifier (cage number), list of devices (eg. wheel/enrichments), and list of co-housed subjects
