### ISSUE TITLE
Minor notes on processing schema

### ISSUE THREAD

**Issue by kgabor** [AllenNeuralDynamics/aind-data-schema#176]
@sharmishtaa Following up our recent discussion about the processing schema, I have some minor comments:

- What is the difference between a ``code_url`` and a ``pipeline_url``. I guess the former one refers to a github repo, that is installed into a pipeline capsule, while the latter one is the capsule itself.  If so, I think we want to document this.

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/6eb2113d3c31d11160b2840d2ca6c6699ca2d4ed/src/aind_data_schema/processing.py#L41
https://github.com/AllenNeuralDynamics/aind-data-schema/blob/6eb2113d3c31d11160b2840d2ca6c6699ca2d4ed/src/aind_data_schema/processing.py#L56

- Please add ``code_version`` to accompany ``code_url``, like at ``pipeline_version``.

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/6eb2113d3c31d11160b2840d2ca6c6699ca2d4ed/src/aind_data_schema/processing.py#L55

- I guess ``version`` means a github release or tag, or (the first few digits of) a commit hash. I'd suggest documenting this, also with the concept that we use commit hash only for test runs and not for production.

- If we have tile fusing as a separate step, let's be explicit here that this is the preceding step. ``IMAGE_TILE_STITCHING = "Solving for stitiching (alignment) transformations"`` or rename to ``IMAGE_TILE_ALIGNMENT``.

- Beside ``OTHER``, I'd add an ``IMAGE_CHARACTERIZATION`` or ``IMAGE_ANALYSIS`` process that could cover all analysis like jobs, including the background estimation and stitching evaluation.

**Comment by sharmishtaa** [comment]
- About your first point , that would be correct.
- The suggestion for keeping track of code versions seems reasonable. 
- DEFINITELY - Stitching is not a clear term and we should always use alignment or registration . I like IMAGE_TILE_ALIGNMENT
- We can definitely add a list of these as we add processes.

**Comment by saskiad** [comment]
I think the difference between code and pipeline is the code url is to the code for a specific processing step. The pipeline url is to the code for the string of processing steps it is part of. We will create different versions of the pipelines by stringing different steps and versions of steps together - this lets us keep track of both

**Comment by saskiad** [comment]
Adding code_version and IMAGE_TILE_ALIGNMENT.
I'd like IMAGE_ANALYSIS to be more specific if possible. What kind of tasks does this usually include.

**Comment by saskiad** [comment]
> the concept that we use commit hash only for test runs and not for production.

What is the difference between test runs and production in this case?

**Comment by kgabor** [comment]
> > the concept that we use commit hash only for test runs and not for production.
> 
> What is the difference between test runs and production in this case?

My idea was that ``code_version`` should be as mandatory as ``code_url``, because if we just point to a github repo, it may have diverged a lot since the run happened. So even if a run was performed without a proper release tag, then at least a commit hash should be given as ``code_version``. I called this latter situation a test run...

**Comment by saskiad** [comment]
I see. I like requiring the commit hash. I'm happy to add that in.

**Comment by saskiad** [comment]
@kgabor can we close this issue? Or is there something that needs to be done?
