### ISSUE TITLE
Laser power unit type

### ISSUE THREAD

**Issue by miketaormina** [AllenNeuralDynamics/aind-data-schema#184]
Is this meant to be a string? Somehow the default string passes validation, but a different string does not.

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/9439ac3080f812127201948aaac3c944f63859f7/src/aind_data_schema/imaging/tile.py#L18

**Comment by dyf** [comment]
it's meant to be a PowerUnit.  Fixing.
