### ISSUE TITLE
somethings not working

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#196]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saskiad** [comment]
what's the problem?

**Comment by mekhlakapoor** [comment]
> what's the problem?

closing this issue it was made during data club as a demo
