### ISSUE TITLE
Incorporate rorid for institution

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#201]
We have our RORID (https://ror.org/04szwah67)
There is also one for AIBS. Can we start having these added to data description files when data is uploaded?

AIND: [04szwah67](https://ror.org/04szwah67)
AIBS: [00dcv1019](https://ror.org/00dcv1019)

**Comment by saskiad** [comment]
can this be automated during data ingestion?

**Comment by saskiad** [comment]
ah, I thought we already had added the field without having the values figured out! Fixing that now.
