### ISSUE TITLE
Automatically run and commit linters in a pr

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#205]
# User story
As a developer, I want to have a github action run linters and commit the changes, so I don't have to do it manually.

# Acceptance criteria
- [ ] Add a bash script to run all the linters and checks with one command
- [ ] When a Pull Request is opened, then a github action will run the linters and commit the changes before running the format checks.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dyf** [comment]
precommit is a better place for this
