### ISSUE TITLE
Figure out where to store our schemas

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#22]
- [x] (P0) can be queried via HTTP request (REST is fine, but whatever)
- [x] (P0) query-able by schema name (retrieves latest) and also by version
- [x] (P1) browsable in a web page

**Comment by jtyoung84** [comment]
Specs are put here: https://alleninstitute.sharepoint.com/:w:/s/NeuralDynamics/EYuvcyb9IwpIpr4zQx3CD2QBwz-0ZPSSEh7dXkwKQzGHeQ?e=eYGAWk
