### ISSUE TITLE
How to describe craniotomy location/shape

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#221]
center coordinates and size don't work for most of the craniotomies being used. Not sure how best to convey the location of a craniotomy - which is probably important to convey.

**Comment by saskiad** [comment]
Craniotomy diagrams are being added to protocols, so that might have to be what we rely on...

**Comment by saskiad** [comment]
Protocols will meet this need. Instead, I recommend:

- [ ] remove `craniotomy_coordinates_ml`, `craniotomy_coordinates_ap`, `craniotomy_coordinates_unit`, `craniotomy_reference`, `craniotomy_size` from `Craniotomy`
- [ ] assure the `CraniotomyType` enum matches the list of craniotomy protocols we have

Sound good @mekhlakapoor

**Comment by mekhlakapoor** [comment]
@saskiad Sounds good! Once this change is made, we'll probably need to upgrade data-schema in the metadata-service again to reflect the change, but it shouldn't break it. The Craniotomy Types in NSB are: 3mm, 5mm, WHC 2P, WHC NP
