### ISSUE TITLE
associated data

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#222]
Add a field to data description of associated data.

eg. for enhancer virus characterization to link slide scanner images with confocal images; or for ephys to associated mri data with subsequent recordings...

@dyf any objections?

**Comment by dyf** [comment]
Fine, but we should be careful about how we describe the relationship - it probably should be something slightly more than just a list of data asset names, but not much more as it will be a pain. 

This is related to defining input data - we capture it by policy in the name, but it would be good to be explicit about what data went into generating a derived result.
