### ISSUE TITLE
README example fails on "home_cage_enrichment"

### ISSUE THREAD

**Issue by chronopoulos** [AllenNeuralDynamics/aind-data-schema#232]
**Describe the bug**
Following the "simple example" in the README give a pydantic ValidationError "extra fields not permitted", on account of the "home_cage_enrichment" field.

**To Reproduce**
1. pip install aind-data-schema (version 0.12.21)
2. Copy+paste the "simple example" code from the README.md into a script.
4. Run the script.
5. See error: 
```
Traceback (most recent call last):
  File "./test_ads.py", line 8, in <module>
    s = Subject(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Subject
home_cage_enrichment
  extra fields not permitted (type=value_error.extra)
```

**Expected behavior**
Run without error, write to subject.json

**Desktop (please complete the following information):**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by dyf** [comment]
@chronopoulos Thanks. You can use `examples/subject.py` instead while I get this fixed.
