### ISSUE TITLE
Schema Diagrams

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#248]
**Is your feature request related to a problem? Please describe.**
It would be helpful for users/developers to have some visualization of our schemas

**Describe the solution you'd like**
Write a script  that will autogenerate diagrams for all the pydantic models in aind-data-schema using erdantic. 

**Additional context**
https://pypi.org/project/erdantic/

**Comment by saskiad** [comment]
It would be good to add these to the repo documentation.
