### ISSUE TITLE
NCBI taxonomy for species to subject

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#257]
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

eg. for mouse: NCBI:txid10090

**Comment by saskiad** [comment]
@Sun-flow This is similar to the issue for MGI alleles, but I expect will be much easier as we have a short list of species that we already know. So maybe start with this before tackling the MGI allele one

**Comment by Sun-flow** [comment]
Plan to solve:
- Introduce class similar to BaseName, which takes inputs for species name, PID, and database info was acquired from
- PIDName(name=str,ID=str,database=str)
- Will place in base, and utilize in subject.species

**Comment by saskiad** [comment]
closed by #294
