### ISSUE TITLE
add schema_version OptoStim model

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#268]
OptoStim does not have schema_version, leading to validation errors

**Comment by saskiad** [comment]
Hmm... I think the solution here is to make OptoStim AindModel rather than AindCoreModel. It's possible we want StimulusPresentation to be AindCoreModel? Or do neither of them need version? Thoughts @dyf

**Comment by dyf** [comment]
Will stimulus information be tracked in its own JSON file? If so, it should be an `AindCoreModel`.

**Comment by saskiad** [comment]
No, I think this should be a class inherited into ephys/ophys models

**Comment by saskiad** [comment]
closed PR #279
