### ISSUE TITLE
imaging-calibration

### ISSUE THREAD

**Issue by miketaormina** [AllenNeuralDynamics/aind-data-schema#272]
**Issue**
Certain aspects of data acquisition do not neatly fall into the `instrument` or `acquisition` categories, but are needed to apply to one or more acquisition instances and are likely to change frequently. Two examples on the SmartSPIM are laser power and flat-field correction images, the first needing a measured correspondence between "percent on" and "milli Watts at objective" and the second needing one or more 2D images be acquired to represent the DC response of the instrument.

These two examples are the ones that will immediately be solved by this feature.

**Proposed Solution**
I would like to suggest a new metadata schema to track either this information directly (in the first example's case) or a way to locate/compute this information (in the second example's case, a file path or the amplitude/phase of a cosine approximation for flat field). I envision other experimental modalities requiring similar parameters be tracked for periodic instrument calibration.

**Describe alternatives you've considered**
It may be possible to shoe-horn these into an acquisition or instrument instance, but a separate schema makes sense for a few reasons:
1. Calibration data can be generated too frequently to warrant inclusion in `instrument.json`.
2. Even if done once per day, a single instrument calibration may apply to several acquisitions.
3. Acquisition metadata can be generated from instrument output, while calibration data is inherently user-generated.

**Comment by saskiad** [comment]
I'm a bit reluctant to add a new schema because I think it doesn't quite solve the issue but just punts it. But I'm a little bit confused. Can you unpack a bit how often you expect the laser power to be calibrated and how often the flat image is acquired. 
Something that is calibrated once a day can be referenced in the acquisitions schema. And multiple acquisitions can reference the same calibration data.
Something that is calibrated less frequently should probably live in the instrument - and the instrument can be updated with each calibration (incrementing the version) - even if that's the only thing changing.
There's probably some threshold of update frequency at which we put it in the instrument vs the acquisition, but I think we can figure something out for that.

Is 100% of the acquisition metadata is instrument generated? I think we can work on a system to make sure that calibration data can be added to that the json.

**Comment by saskiad** [comment]
That sounds good! Thanks Mike!

**Comment by miketaormina** [comment]
Finally got around to roughing this out in `acquisition.py.`
# Summary
I assumed a linear relationship between a laser set point and the power measured at the sample, but I guess this accommodates multiple entries, so is generalizable if people get crazy with it.

Added classes:
1. `PowerUnit(Enum)`
2. `LightSourcePowerCalibration(AindModel)`. Tracks light source, excitation arm, power setting, and power measurement (with units).

Added to `Acquisition`:
1. `calibrations: Optional[List[LightSourcePowerCalibration]]`

## Things I wasn't sure about:
- in the main class, there is a `light_source` variable for, e.g., which laser a given measurement is for. It is of type `imaging.instrument.LightSource`, to try to encourage conformity with the instrument in question. Not sure if this should rather just be a name.
- also in `LightSourcePowerCalibration`, there is an integer designation `illumination_index`, which is how the left/right excitation arms are designated in the microscope-generated metadata. I don't think the separate excitation arms are modeled in `instrument.json`, so this seemed the most useful.
- Not sure if this will be the only calibration or if flat-field corrections will eventually go here, which is why I used the more general name `calibrations` in the `Acquisition` class. I was thinking that if more types get added in the future, there can be a `calibration_like = Union(...)` way to make the list.

# Use by an operator
I was thinking that the best way (for SmartSPIM) would be a small python gui where the operator fills in fields for lasers, sides, measurements, etc. and a JSON gets generated into the `SmartSPIM_Data/2023_06_16/` directory (where each raw data set for that day will go). This file can ride in the `derivatives` folder and get interpreted when creating `acquisition.json`. `derivatives`, by the way, is where I've been stuffing the flat-field images.

**Comment by miketaormina** [comment]
Added `smartspim_power_calibrations.json`, which can be ingested when building `acquisition.json`.

This was generated with a rough input GUI that will follow in another repo.
