### ISSUE TITLE
Remove unused coordinates in ephys rig

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#282]
@jsiegle @dyf There are several size/position classes in the ephys rig schema that aren't being used:
Size2d
Orientation3d
ModuleOrientation2d
ModuleOrientation3d
Coordinates3d

I'd thinking we should remove these, but want to make sure I'm not missing something. LMK if I should not remove them.

**Comment by jsiegle** [comment]
Yeah, I think these are no longer needed.

**Comment by saskiad** [comment]
closed by PR #288
