### ISSUE TITLE
Add HARP as a Manufacturer

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#285]
@jsiegle I assume HARP is the Manufacturer of HARP devices?

**Comment by jsiegle** [comment]
No, we currently get these devices from OEPS, which is set as the default manufacturer. In the future these may be built in-house or purchased elsewhere.

**Comment by saskiad** [comment]
ah, I see that. I think there might be a glitch with the web UI then. I'll track that down.

Can you tell me what OEPS stands for?

**Comment by jsiegle** [comment]
Open Ephys Production Site

**Comment by saskiad** [comment]
@mekhlakapoor when I use the web app to make a ephys rig json, when I add a HarpDevice I see the full list of manufacturers, while in the schema it is actually hardcoded as being OEPS. Is this something we can fix? (And maybe check some other places where we limit our list of manufacturers in the schema to see how they show up in the app?

**Comment by mekhlakapoor** [comment]
It looks to only be an issue for HarpDevice (other device types will automatically have the correct defaulted manufacturer). I think it might be because Harp Device. Also found that if I select OEPS in the enum, it changes the device to "DAQ Device" ?

**Comment by jtyoung84** [comment]
@mekhlakapoor Can you take a look into whether this is still an issue or not?
