### ISSUE TITLE
remove describedby from AindCoreModel classes

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#286]
The describedBy field is automatically created for the children models of AindCoreModel because the field is defined in AindCoreModel's definition, so we don't need describedBy in the class definitions of said children models.

# Acceptance criteria
- [ ] Remove describedBy from ephys_rig class
- [ ] go through aind-data-schema to check for any other classes (that inherit from AindCoreModel) that have describedBy fields and remove it

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by Sun-flow** [comment]
wow !!

**Comment by saskiad** [comment]
- [ ] ephys rig
