### ISSUE TITLE
Can't import Axis

### ISSUE THREAD

**Issue by lydiang** [AllenNeuralDynamics/aind-data-schema#29]
**Describe the bug**
The python statement:
`from aind_data_schema import Axis`

Generates the following error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15328/372763372.py in <module>
----> 1 from aind_data_schema import Axis

ImportError: cannot import name 'Axis' from 'aind_data_schema' (c:\users\lydian\onedrive - personal\onedrive\work\aind-data-schema\src\aind_data_schema\__init__.py)

```

**To Reproduce**

**Expected behavior**
I am able to import Axis like I do Acquisition, Subject, LightCycle etc.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dyf** [comment]
Thanks @lydiang. Fixing this shortly.

**Comment by dyf** [comment]
Workaround: `from aind_data_schema.imaging.acquisition import Axis`

**Comment by lydiang** [comment]
Workaround is working
________________________________

**Comment by dyf** [comment]
@lydiang right now Axis in a couple modality-specific places. going to refactor before taking this.
