### ISSUE TITLE
Full names for manufacturers

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#291]
There are several manufacturers listed only by their abbreviation. I'd like us to know what who these are. @dyf does it make sense to use the BaseName class here? My worry with that is that we don't have abbreviations for all manufacturers.

Specific examples:
OEPS = Open Ephys Production Site
IMEC
FLIR
LG
MPI

I think for some of these we want to use the abbreviation in most instances (eg. IMEC) but I also think we want to know what these all are.

**Comment by Sun-flow** [comment]
BaseName has optional abbreviation I believe, so it shouldn't be an issue to use.

**Comment by jtyoung84** [comment]
Duplicate of other ticket
