### ISSUE TITLE
Add ROR IDs for Institutions in data description

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#298]
Like the species IDs, this is a short and finite list using this registry: https://ror.org/

The thing we need to consider here is how to combine BaseName and PIDName. Let's discuss with @dyf next week

**Comment by Sun-flow** [comment]
Making some of the fields optional might be an easy fix? BaseName being the simplest case, with inclusions for things like PID info.

Alternatively BaseName could become an inherited/nested class, which maintains name+ID pairs, and then wrap it with other info as needed.

**Comment by saskiad** [comment]
closed with PR #303
