### ISSUE TITLE
Provide more installation instruction!

### ISSUE THREAD

**Issue by lydiang** [AllenNeuralDynamics/aind-data-schema#30]
**Describe the solution you'd like**

I believe the target audience you want to capture is the scientist who has learnt how to program.
As such consider providing a little more installation instruction.

Re: pip install
- tell them what the command does
- tell them should be in the environment that they want this in
- tell them how to unsinstall

- tell them (and me!) what to do when someone has made changes in the repo and you want to make use of the changes
- - git pull or checkout of whatever
- do I uninstall first etc.

**Comment by dyf** [comment]
@lydiang Great feedback, thank you!  We haven't done any documentation yet, you are a guinea pig :).
