### ISSUE TITLE
Update Interrogate documentation for clarity to naive user

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#300]
Currently documentation in readme surrounding features like interrogate, flake, black, etc are not documented with use or solutions. (ie, how to run from terminal and how to solve errors they throw)

**Comment by Sun-flow** [comment]
I'm making a branch for this, which I will include the documentation updates I have been walked through today. Please feel free to add your own to the branch

**Comment by Sun-flow** [comment]
branch: https://github.com/AllenNeuralDynamics/aind-data-schema/tree/docs-300-improve-readme

**Comment by jtyoung84** [comment]
Let's break this down into smaller issues...
