### ISSUE TITLE
Refactor BaseName into PIDName + determine naming conventions

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#302]
BaseName is implementing a rudimentary version of PIDName, these can be refactored into a class with optional fields to cover relevant data. 
existing data:
- Name (species name, institute name, etc)
- registry (name where was information acquired from)
- registry abbreviation (short name, or acronym)
- reference ID (for species code, institute number, registryID etc)

**Comment by Sun-flow** [comment]
Does anyone know how utilizing a custom class works with our Field(...,) values?

for instance, PIDName inheriting BaseName to some degree like:

class PIDName(AindModel):
    """Model for associate a name with a persistent identifier (PID) and the registry for that PID"""
    
    name: str = Field(..., title="Name")

becomes:

class PIDName(AindModel):
    """Model for associate a name with a persistent identifier (PID) and the registry for that PID"""
    
    name: BaseName = Field(..., title="Name","Attribute") <-- you can see here that labeling for fields gets weird with this inheritance

**Comment by saskiad** [comment]
would something work like:

`class Institution(Enum, metaclass=BaseNameEnumMeta):
    """Institution name"""

    AIBS = PIDName(name=BaseName(name="Allen Institute for Brain Science", abbreviation="AIBS"), registry="ROR", registry_identifier="xxx")
    AIND = PIDName(name=BaseName(name="Allen Institute for Neural Dynamics", abbreviation="AIND"), registry="ROR", registry_identifier="yyy")
`
I'm guessing we'd have to add PIDName to the metaclass at the top? I don't actually know about that part. @dyf does this make sense?

**Comment by saskiad** [comment]
(also, the formatting on that got wonky - I'm not good with formatting on here)

**Comment by saskiad** [comment]
I think if that works, we don't need to refactor BaseName or PIDName, just use them together

**Comment by Sun-flow** [comment]
@saskiad I think this would work for instantiating a variable, but specifically with the Field(...,[content]) im not sure how i would handle things. Ie, 
`name: BaseName(name,abbreviation) = Field(..., title="Name, abbreviation")`

**Comment by Sun-flow** [comment]
Maybe there is a way for me to utilize field twice, for one variable?

**Comment by dyf** [comment]
@mae the Enums are defining `PIDName` instances, so I think what @saskiad said is correct.

**Comment by saskiad** [comment]
> @saskiad I think this would work for instantiating a variable, but specifically with the Field(...,[content]) im not sure how i would handle things. Ie, `name: BaseName(name,abbreviation) = Field(..., title="Name, abbreviation")`

So I don't know that you need to define a new field here, I think it's just using the BaseName when you make the enum list
