### ISSUE TITLE
update import path conventions to be consistently absolute/relative

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#308]
In aind_data_schema, there are inconsistencies in pathing conventions. Some are absolute while others are relative. 

@jtyoung84 has mentioned a preference for absolute paths, and that this could be done sometime as a QOL update. 

Acceptance Criteria:
- [ ] All imports are consistently absolute

**Comment by dyf** [comment]
I'm good with absolute paths.

**Comment by saskiad** [comment]
me too!

**Comment by dyf** [comment]
Updated the acceptance criteria
