### ISSUE TITLE
Add experiment type and modality for mesoscope and slap2

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#311]
We need a modality to capture data being collected on various flavors of mesoscope and the slap2.

Acceptance Criteria:
- Add Modality for mesoscope/scientifica/multiscope/bergamo
    - name: "Planar optical physiology"
    - abbreviation: "POPHYS"
- Add ExperimentType: POPHYS = Modality.POPHYS
- Add Modality for slap2
    - name: "Scanned line angular projection"
    - abbreviation: "SLAP"
- Add ExperimentType: SLAP = Modality.SLAP

Don't do this just yet, confirming the names still.

**Comment by saskiad** [comment]
For slap2:
name: "Scanned Line Projection"
abbreviation: "SLAP"
