### ISSUE TITLE
utility function to return all model classes

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#316]
Using inspect function to return all model classes currently imported

**Comment by Sun-flow** [comment]
Defining AindUtils class for placing generic functions. 
- contains function _get_classes(module), which returns all classess imported into model
- _get_schemas could be moved here, and then refactored out of json_writer + erd_diagram generator

**Comment by Sun-flow** [comment]
I have gone ahead and put _get_schemas into AindUtils, and will refactor json_writer + erd_generator once mergeds

**Comment by jtyoung84** [comment]
@dyf Acceptance Criteria
