### ISSUE TITLE
Identify which CO Data assets are missing metadata

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#329]
ie, 

file 'ecephys_625463_2022-09-30_14-37-42'
- missing subject, procedures, rig, session

Need to comb Data Assets to find these holes, populate a DF with TF columns denoting what metadata are present

Try to include contact for who can help populate that data (institution [in data_desc file], if there is session/acquisition there should be an experimenter field that can help)

**Comment by dyf** [comment]
Let's do this one once the session.json converter is written.

**Comment by Sun-flow** [comment]
@dyf Want to check in on this, since you wanted to wait until some other condition had been satisfied. I will move this to backlog, if that condition has not been met yet.

**Comment by dyf** [comment]
Thanks, don't really remember. I think it's safe to start on this.

**Comment by Sun-flow** [comment]
Starting work on this, it feels weird to write code for this in aind-data-schema? Feels like the sort of thing that writes code similar to what I do in aind-data-migration-scripts. Just want to check in on where we think the most appropriate place to store relevant code would be. @dyf @jtyoung84

**Comment by Sun-flow** [comment]
Actually, I've really already written this code for a different PR. https://github.com/AllenNeuralDynamics/aind-data-migration-scripts/blob/0db375668f4100943cbe8ae390f71a3d11031f13/scripts/2023-06-08/fix_u19_smartspim.py#L137

I can write it into its own file that does exclusively this, and if there are any other files we want to search for I can add those.

**Comment by Sun-flow** [comment]
closing with completion of basic implementation: https://codeocean.allenneuraldynamics.org/capsule/5867079/tree

follow up tasks are detailed in comments, new ticket for follow up work
