### ISSUE TITLE
Expand Utils.Units enums to cover existing units used in schema

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#330]
Utils.Units has been merged into main as a structural system, but needs to be fully fleshed out with all relevant unit types.

Current types are:
- Size
- Mass
- Frequency
- Volume
- Angle
- Time

Others will be searched for using find in files feature, with search term _units.

Please advise if there are any specifics that would not be found this way.

**Comment by jtyoung84** [comment]
Duplicated issue
