### ISSUE TITLE
Add RORIDs to Manufacturers

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#343]
- [ ] get list of RORIDs available for our current list of Manufacturers
- [ ] Add RORID to device schema with Manufacturer (similar to Institution)

**Comment by Sun-flow** [comment]
@saskiad where can I get RORIDs for manufacturers?

**Comment by saskiad** [comment]
https://ror.org/

**Comment by Sun-flow** [comment]
Brief scan is returning no RORIDs for manufacturers. Seems like an empty search.

**Comment by saskiad** [comment]
I've added a number of ids for some of the manufacturers. Many are not there, but several are
