### ISSUE TITLE
Bug with Species

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#356]
**Describe the bug**
species in the subject model is expected to be of type Species. However, this then results in one of two errors -- if the species is defined as species=Species.MUS_MUSCULUS, the value of species will be of type PIDName, which is not JSON serializable. if it's defined as species=Species.MUS_MUSCULUS.name (type str), then it throws a pydantic error. 

**Expected behavior**
I think species should expect a string instead, and subject models can define species as species=Species.MUS_MUSCULUS.name

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jtyoung84** [comment]
I don't think this is necessarily a bug. It is json serializable. The class may need to be modified to allow it to be set by the enum name. You can see how it's being done in the data description module using this meta class: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/base.py#L39

**Comment by mekhlakapoor** [comment]
this is the validation error: 
`pydantic.error_wrappers.ValidationError: 1 validation error for Subject
species
  value is not a valid enumeration member; permitted: PIDName(name=BaseName(name='Callithrix jacchus', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9483'), PIDName(name=BaseName(name='Homo sapiens', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9606'), PIDName(name=BaseName(name='Macaca mulatta', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9544'), PIDName(name=BaseName(name='Mus musculus', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='10090') (type=type_error.enum; enum_values=[<Species.CALLITHRIX_JACCHUS: PIDName(name=BaseName(name='Callithrix jacchus', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9483')>, <Species.HOMO_SAPIENS: PIDName(name=BaseName(name='Homo sapiens', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9606')>, <Species.MACACA_MULATTA: PIDName(name=BaseName(name='Macaca mulatta', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='9544')>, <Species.MUS_MUSCULUS: PIDName(name=BaseName(name='Mus musculus', abbreviation=None), registry=BaseName(name='National Center for Biotechnology Information', abbreviation='NCBI'), registry_identifier='10090')>])`

**Comment by mekhlakapoor** [comment]
> I don't think this is necessarily a bug. It is json serializable. The class may need to be modified to allow it to be set by the enum name. You can see how it's being done in the data description module using this meta class: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/base.py#L39 You could then set it as `s = Species("MUS_MUSCULUS")` Probably modifying the subject module and class to something like:
> 
> ```
> from aind_data_schema.base import AindCoreModel, AindModel, BaseName, PIDName, BaseNameEnumMeta
> 
> 
> class Species(Enum, metaclass=BaseNameEnumMeta):
> ```
> 
> should fix it

it is JSON serializable when generating it in subject.py, but I get this type error in the metadata-service from model_response
`TypeError: Object of type PIDName is not JSON serializable`

this is what is particularly throwing the erro
`response = JSONResponse(
                status_code=StatusCodes.VALID_DATA.value,
                content=(
                    {
                        "message": "Valid Model.",
                        "data": model_json,
                    }
                ),
            )`
where the model definition looks like this
`model = Subject(
            species=Species.MUS_MUSCULUS,
            subject_id="639374",
            sex="Male",
            date_of_birth="2022-06-24",
            genotype="Pvalb-IRES-Cre/wt;RCL-somBiPoles_mCerulean-WPRE/wt",
        )`
