### ISSUE TITLE
`TissuePrep` should be a `Procedure`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#38]
Looks like it fits the mold, would just need to override the `type` field instead of using `name`.

**Comment by saskiad** [comment]
the key difference is that TissuePrep has date_started and date_ended while Procedure has date

**Comment by dyf** [comment]
ah, I see. well up to you if you want to take this.

**Comment by saskiad** [comment]
we could have a start and end date for all procedures, which will usually be the same, but for tissue prep they won't. That might make Training protocols something we can conform to the same procedures object as well...

**Comment by dyf** [comment]
I like that.

**Comment by saskiad** [comment]
I wonder if there should be procedures for animals separate for procedures for tissue? subject vs specimen?

**Comment by saskiad** [comment]
and training protocol can't conform to procedure because there will won't be a single experimenter

**Comment by dyf** [comment]
We could make experiment a list always?

________________________________

**Comment by saskiad** [comment]
I think that there's going to be training data, similar to session data. So I think that's where the experimenter of training sessions should live. Here we simply want a record of "we did this training protocol starting day x ending day y"... I think...

**Comment by dyf** [comment]
closed by #63
