### ISSUE TITLE
Map MGI allele ids

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#380]
We want to add the MGI allele ids to the subject schema. This requires us to create a map of genotype names to a list of MGI alleles.

- [x] create list of all unique genotype from the doc DB
- [x] separate allelles
- [ ] create a preliminary map of allele names to MGI ids. 
- [ ] flag the alleles for which this mapping is unsure for follow up

**Comment by Sun-flow** [comment]
- find all genotypes that we are using, can be found in the subject file on docDB 
- example genotype: Cux-CreERT2/wt;Camk2a-tTA/wt;Ai93/Ai93
- alleles: ['Cux2-CreERT2', 'Camk2a-tTA', 'Ai93']
