### ISSUE TITLE
2 MousePlatform's in device module

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#405]
**Describe the bug**
There are 2 MousePlatform definitions in the device module that were probably created separately for ephys_rig and behavior. However, this is confusing and could be causing errors for child models. 

**To Reproduce**
1. Go to aind-data-schema device module line 530
2. Go to aind-data-schema device module line 608

**Expected behavior**
Clean this up (redefine the names and inheritance to ensure it's as expected).
<img width="754" alt="MicrosoftTeams-image (2)" src="https://github.com/AllenNeuralDynamics/aind-data-schema/assets/54870020/35ab6088-dc23-446f-a796-43f959804f76">
<img width="719" alt="MicrosoftTeams-image (1)" src="https://github.com/AllenNeuralDynamics/aind-data-schema/assets/54870020/593df6fa-2360-4116-a290-001b0d824f57">

**Screenshots**

**Additional context**
_Originally posted by @jtyoung84 in https://github.com/AllenNeuralDynamics/aind-data-schema/pull/403#pullrequestreview-1517640710_

**Comment by saskiad** [comment]
This is resolved in #425
