### ISSUE TITLE
tweaks to HCR schema, additional HCR StainTypes and Fluorophores

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#409]
Issues
- it is hard to represent a DAPI stain right now as part of a codebook
- rounds are acquired at different times and processed independently, so making the whole `HCRSeries` the procedure doesn't quite fit. likely the HCR round needs to be the procedure, and the codebook is a reference that follows it along to communicate intention.
- classes are not well defined
- missing stain types
  - Reporter
  - Fill
  - Nuclear
  - Registration
- missing fluorophores (just check with http://aidc-mfishlightsheet/record-keeper/fluorophores)

**Comment by saskiad** [comment]
1. yeah, I think DAPI would fall under other_probe, but that still requires a sequence and DAPI probably doesn't have one. Let's fix that
2. current structure reflects the separate acquisition of rounds. We went back and forth on this before and I still think we need the HCRSeries to be the fundamental procedure. The codebook isn't really a reference so much as the documentation of which channel is what.
3. need more detail
4. this also isn't clear. 
5. we can add fluorophores.

**Comment by saskiad** [comment]
remove channel index from OligoProbe

**Comment by saskiad** [comment]
@dyf can we confirm that other fluorophores are being used. I don't see any examples that use fluorophores other than the 3 we already have. I'm reluctant to add to the list unless we are sure we are going to use others.

**Comment by saskiad** [comment]
- Reporter and registration are not stain types. 
- Current list of fluorophores is accurate to what is being used
