### ISSUE TITLE
Surgical Procedures 

### ISSUE THREAD

**Issue by maclennanb** [AllenNeuralDynamics/aind-data-schema#418]
Currently, surgical procedures like Headframe, Nanoinject Injections, and Fiber implants are treated as separate procedures such that for every injection and every fiber I am prompted to enter the date, and time under anesthesia repeatedly. Generally, these are all done as one "Surgical Procedure." To me, it would make more sense to have a level above these individual subject procedures called "Surgery" or "Surgical Procedure" where general info about time, date, anesthesia duration, animal recovery time etc. can be entered only once, then injections, craniotomies, fiber implants can be added to this "Surgical Procedure."

**Comment by hagikent** [comment]
I'm circling back to this. I also feel it's even confusing to have multiple times of "isoflurane 2h" in procedure metadata. General procedures incl anesthesia should be shared across individual action eg injections/implants.
