### ISSUE TITLE
Platform instead of Experiment Type

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#450]
# User story
`experiment_type` is too confusing. When a user creates a DataDescription model, the `experiment_type` will be replaced by a `platform` field.

# Acceptance criteria
- [ ] `platform` is a new required field of type `Platform`, which is an `Enum` of `BaseNames`
- [ ] The available `Platform`s match the known platforms we are supporting.
- [ ] A validator that validates only alpha-numeric and dashes are in `platform.abbreviation`
- [ ] There is a "data_name" property method that returns a default data_asset_name as `{platform.abbreviation}_{subject_id}_{acq_date}_{acq_time}`

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dyf** [comment]
Update: this is waiting on a final project list from the admin team, arriving ~next week.

**Comment by dyf** [comment]
this was closed by #452
