### ISSUE TITLE
Cannot initialize a rig with DAQs that are connected to each other via a channel

### ISSUE THREAD

**Issue by sburckha-aind** [AllenNeuralDynamics/aind-data-schema#458]
When creating a rig object, if a list of DAQs is provided (e.g. daqs = [basestation, nidaq0, nidaq1]), if basestation is connected to nidaq0 via one of its channels (in the "channels" field), the program will fail when adding basestation to the rig, claiming that nidaq0 is mentioned in a channel but not part of the rig. In other words, even though the second DAQ device would be added to the rig in the next step, adding the first one fails because the second does not exist yet.

There is a workaround for this, which is adding the DAQ devices to the rig first with no channels, and then initializing rig.daqs[i].channels afterwards, but I feel that this was an oversight, as it should be possible to initialize all your devices and channels first and add them to the rig at the very end as the last step.

![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/143029713/02e5c5eb-3ff1-4815-bf43-c162e4d09c76)

In this case, the code is failing when trying to add basestation to the list of DAQs, as basestation's channel mentions nipx, which is not a part of the rig (yet).

**Comment by jsiegle** [comment]
Thanks for posting this Sasha! I will take a closer look on Friday

**Comment by jsiegle** [comment]
The `EphysRig` validator previously did not check for connections *between* `DAQDevice` objects...this was definitely an oversight. This issue should be fixed with this PR: https://github.com/AllenNeuralDynamics/aind-data-schema/pull/476
