### ISSUE TITLE
Single Manufacturer list

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#47]
Create a single manufacturer list - perhaps for specific modalities, perhaps for all modalities?

**Comment by dyf** [comment]
I went back and forth on proposing this @saskiad. Having very specific manufacturer lists is nice for validation (e.g. you can't pick an ephys manufacturer for a camera filter). But it's also a hassle.

I think my vote is single manufacturer list.  It's really not that long of a list and will be nice to have in one place.
