### ISSUE TITLE
Create json files of schema

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#474]
**Is your feature request related to a problem? Please describe.**
For integrating with Bonsai (e.g.) which doesn't already have python integration. Easier to get metadata from Bonsai into schema

**Describe the solution you'd like**
Store json files of schemas in the repository. GitHub action to create json files upon merge

**Additional context**
Based on discussion with Bruno and Josh

**Comment by dyf** [comment]
@saskiad we have all versions in JSONSchema in an S3 bucket.  would that work?

**Comment by dyf** [comment]
I showed these to Bruno, I think we are covered.
