### ISSUE TITLE
Specify timezones for datetimes

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#484]
For datetimes to be useful, we need to specify the timezone.  

Acceptance criteria:

- [ ] all `datetime` type fields include the timezone when serialized
- [ ] the serialized string is in the timezone local to the client that generated the string. For example: "Jan 1 2023 8am", when generated in Seattle, should look like this: `2023-01-01T08:00:00-07:00`

Notes:
- light cycle should be a `time`, not a `datetime`, as it is not a specific point in time.

**Comment by saskiad** [comment]
remove the UTC specification in the light cycle description

**Comment by bruno-f-cruz** [comment]
Would it be possible to also accept [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) I tend to prefer using this standard since it does not rely on the ability to parse and correct the timestamp data posthoc.

**Comment by jtyoung84** [comment]
Will be resolved when aind-data-schema is using pydantic v2

**Comment by saskiad** [comment]
@Sun-flow is this still blocked now that v2 update is finished?

**Comment by jtyoung84** [comment]
@Sun-flow Here is an example of how this can be implemented:
```python
from datetime import datetime, timezone
from pydantic import AwareDatetime, BaseModel, Field

class Foo(BaseModel):
  dt: AwareDatetime = Field(...)

foo = Foo(dt = datetime.now(tz=timezone.utc))

foo_json = foo.model_dump_json()
print(foo_json)
# '{"dt":"2024-01-25T01:24:44.624234Z"}'
Foo.model_validate_json(foo_json)
# Foo(dt=datetime.datetime(2024, 1, 25, 1, 24, 44, 624234, tzinfo=TzInfo(UTC)))

# It seems like it supports parsing strings directly. The following also work

# foo2 = Foo(dt = '2012-11-01T04:16:13-04:00')
# foo2 = Foo(dt = "2024-01-25T01:24:44Z")

# Errors will be raised if the user doesn't provide a timezone
# This will raise an error:
# foo2 = Foo(dt = datetime.now())
# People will have to add an extra line to capture timezone:

foo2 = Foo(dt = datetime.now().astimezone())
```

**Comment by galenlynch** [comment]
To be a bit clearer: if a naïve datetime is given to the library, and the current timezone (as a UTC offset) is applied to that datetime, then the resulting time will be wrong if the original datetime was from a different time offset at the same location. For example, if someone is now uploading data collected before daylights savings, then some implementations could produce wrong datetimes.

I think requiring that users supply their own time zone could also be tricky, as they could easily get it wrong, too. Ideally this library would "do the right thing" when it is given a naïve datetime.

**Comment by bruno-f-cruz** [comment]
Not sure I follow, ISO 8601 as a standard has the expressivity to handle timezones (or just write something in "raw" UTC). The json schema defines a spec of how the dates should be serialized and eventually parsed, it should not decide as to how the backend implementation arrives at those dates.

**Comment by jtyoung84** [comment]
I think we're going to try to extract the locale from the user's computer settings as a default if it isn't supplied.

**Comment by galenlynch** [comment]
ISO 8601 is great for serialization, I think we should use it. 

I'm just worried about the backend implementation to arrive at those dates. Even using the user's locale could be fraught, if aind-data-schema is being used to generate data collected in the past.

For example, if we are using a open ephys settings.xml file to find when a session started, people might write something like this:
```python
import datetime
# This part happens in client code
naivedatetime = datetime.datetime.strptime("28 Feb 2024 18:00:37", "%d %b %Y %H:%M:%S") # Open Ephys time stamp

# This part might happen somewhere in this library
# Note, this depends on when you run the code, which is the point. I ran this on 2024-03-13
user_tz = datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo # An approach to get local timezone for user
awaredatetime = naivedatetime.replace(tzinfo=user_tz)
print(awaredatetime)
# 2024-02-28 18:00:37-07:00
#               Wrong ^^^^^ should be -08:00 because of daylight's savings
```

An effort should be made to handle naive datetimes that happened at different offsets (because they happened on different days) than the user's current offset.

I think using IANA tz codes would be better for the backend code handling naive datetimes, or some other way of ensuring these sorts of bugs don't happen.

**Comment by galenlynch** [comment]
Maybe if this library is only viewed as a way to serialize user-supplied data, then this is out of scope. But that then puts the burden of doing this correctly on all the users. I would bet a lot of client code would be slightly buggy. 

Maybe an hour twice a year isn't a big problem.

**Comment by jtyoung84** [comment]
I'll look into it some more. My hope is that pydantic will handle the serialization/de-serialization. I'll think about how to set defaults and how users can define the timezones.

**Comment by jtyoung84** [comment]
```python
# We can define the field as an aware datetime object
from datetime import datetime, timezone
from pydantic import AwareDatetime, BaseModel, Field

class Foo(BaseModel):
  dt: AwareDatetime = Field(...)


# When a user goes to create a datetime object, they can use several different methods

# To use the locale of the user's computer
foo = Foo(dt=datetime.strptime("28 Feb 2024 18:00:37", "%d %b %Y %H:%M:%S").astimezone())

# To specify using zone info
from backports.zoneinfo import ZoneInfo
foo2 = Foo(dt = datetime.strptime("28 Feb 2024 18:00:37", "%d %b %Y %H:%M:%S").replace(tzinfo=ZoneInfo("America/Los_Angeles")))

# pydantic will handle the serialization:

print(foo.model_dump_json())
{"dt":"2024-02-28T18:00:37-08:00"}

print(foo2.model_dump_json())
{"dt":"2024-02-28T18:00:37-08:00"}
```

**Comment by jtyoung84** [comment]
The main issue we're currently facing is that the datetime fields in our past metadata json files don't have timezone info associated with them. We can also add a check that uses the user's locale if a datetime is passed into the model without any info, but that can be discussed further. We can also just allow it to raise an error.

**Comment by jtyoung84** [comment]
Yeah, we plan to do a thorough quality control check once aind-data-schema is more stable. @saskiad Are you cool with having the default be the locale of the user's computer if a timezone isn't explicitly defined?

**Comment by saskiad** [comment]
yes, I'm good with that.
