### ISSUE TITLE
Add an `AnalysisDescription` subclass of `DataDescription`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#500]
- [ ] follow the pattern of `RawDataDescription` to make an `AnalysisDescription` subclass of `DataDescription` 
- [ ] the name field will have four components: `<project-abbreviation>_<analysis-name>_<date>_<time>`
- [ ] none of these can contain dashes

**Comment by saskiad** [comment]
I'm not sure about the name 'AnalysisDescription' because I instinctively interpret that to mean the analysis code rather than the data asset that comes out of it. But we already have derived data....
