### ISSUE TITLE
Add fiber photometry items to new rig/session

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#505]
For manipulator based fiber photometry.

**Comment by saskiad** [comment]
- [ ] session: fiber_modules: Optional[List[FiberModule]] = Field(None, title="Fiber modules", unique_items=True)
- [ ] session: class FiberModule(ManipulatorModule):
    """Fiber photometry devices recorded in a Stream"""

    fiber_photometry_devices: List[FiberPhotometryDevices] = Field(..., title="Fiber photometry devices used in this module")

- [ ] We should add something like this for fiber photometry on the ephys rig:

class ImplantableFiber(Device):
    """Named fiber optic used in an acute experiment"""
    # required fields
    length: SizeUnit = Field(SizeUnit.MM, title="length unit")
    diameter: SizeUnit = Field(SizeUnit.MM, title="diameter unit")
    taper_length: SizeUnit = Field(SizeUnit.MM, title="diameter unit")


class FiberAssembly(AindModel):
    """Module for fiber photometry recording"""

    fiber_assembly_name: str = Field(..., title="Fiber assembly name")
    manipulator: Manipulator = Field(..., title="Manipulator")
    fibers: List[ImplantableFiber] = Field(..., title="Fiber optics that are held by this module")
Also, it looks like fiber photometry devices are currently listed in session.py, but not devices.py, so they won't be included in the rig file. Is this intentional?

**Comment by saskiad** [comment]
@jsiegle I'm looking to integrate this now, but I'm worried there's too much confusion between the fiber photometry classes that already exist. I might need to find some time for you me and kenta to discuss. Anyone else I should loop in?

**Comment by jsiegle** [comment]
Chatting with me and Kenta sounds good!
