### ISSUE TITLE
Modality specific validators for rig and session schemas

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#509]

**Comment by Sun-flow** [comment]
@saskiad could you please add a description to this with a bit more detail on what you would like to be validated?

**Comment by saskiad** [comment]
Here's my first pass - I might be missing something. A lot of these are not exclusive. Eg. ecephys can have light_source but it's not required for ecephys.

For Rig:
If ecephys modality, need ephys_assemblies, stick_microscope
If FIB: need light_source, detector, patch_cords
if pophys: need light_source, detector, objective
If slap need light source, detector, objective (this will probably be a longer list soon)
If behavior_videos: need cameras
if trained_behavior: need stimulus_devices

For session (some of these are in the Stream class):
Ecephys: need stick_microscopes, ephys_modules
FIB: need light_source, detector, fiber_photometry_assemblies
POPHYS: need either ophys_fov OR stack_parameters ... not sure that's possible
SLAP: not sure yet, hold off on this
Behavior_videos: camera_names
Trained_behavior: stimulus_device_names
