### ISSUE TITLE
Add new vendors for Imaging schema

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#512]
**Is your feature request related to a problem? Please describe.**
Missing vendors for Imaging schema

**Describe the solution you'd like**
Add these vendors below

Olympus
Mitutuyo
AA Opto Electronic
Vieworks
Euresys

**Describe alternatives you've considered**
Currently just using Manufacturer.OTHER but would prefer to have them explicitly added to the manufacturers list.

**Comment by saskiad** [comment]
@adamkglaser do these need to be added to any specific device classes?

**Comment by saskiad** [comment]
Olympus and Vieworks are already in the Manufacturer list.

**Comment by adamkglaser** [comment]
No specific class I was just thinking to this list? https://github.com/AllenNeuralDynamics/aind-data-schema/blob/773ee35126cb91689a0254d9d561b55f04093233/src/aind_data_schema/device.py#L23

**Comment by saskiad** [comment]
@Sun-flow the manufacturer list has moved with the recent merge, but should be easy to add these. Note that two of these are already in the list, and none of the new ones have ROR Ids (feel free to double check, but I only found Olympus in ror ... which we already have)
