### ISSUE TITLE
Audio devices

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#530]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be a specific schema for audio devices. Are there any plans to associate audio devices with `EphysRig` in a more structured way beyond the `additional_devices` field.

**Describe the solution you'd like**
Audio devices could be included as an additional field on `EphyRig`.

**Comment by dyf** [comment]
@saskiad 

@mochic are there particular parameters you want to track on audio devices?

**Comment by saskiad** [comment]
Is this different from the speaker class we already have?

**Comment by mochic** [comment]
Nope that is definitely what we need thanks!
