### ISSUE TITLE
Add compute resource usage to processing.json

### ISSUE THREAD

**Issue by camilolaiton** [AllenNeuralDynamics/aind-data-schema#536]
It is important to track compute resources whenever we are running our scripts in order to optimize our algorithms. Therefore, I propose that we include that in the `processing.json`. @dyf @saskiad 

These are some of the important info I am adding to the new versions of the SmartSPIM capsules:

![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/36769694/17c0fb58-ecf1-4da5-b68d-9b25fd787b6b)

Information about operative system, compute resources and its peak usage could be very important but could not be limited to only these. The usage of compute resources over time/step could also be very important to track.

![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/36769694/6c255c24-bed4-45c9-99e1-9d2828e472b2)

**Comment by saskiad** [comment]
I think we should move on this - the idea has come up in a couple of conversations and I think implementing this would be helpful.

**Comment by saskiad** [comment]
need specs

**Comment by dbirman** [comment]
@camilolaiton is going to provide some more details on what we might want to include here, copying some possible things from above to discuss:

- OS
- CPU info
- GPU info
- cpu/gpu/ram usage snapshots over time
- instance information (cpu/gpu/ram/memory)
- instance costs? not sure how visible that is

**Comment by camilolaiton** [comment]
Personally, I'd like a schema that includes:

1. Operative System (e.g., Linux, Windows, Mint, MacOS, ...) and its version.
2. Machine architecture (e.g., x86_64, we should definitely include bit version).
3. Physical resources (e.g., number of CPU cores, RAM, shared memory compartment, number of GPUs, Disks).
4. Usage of CPU as a percentage over time (I don't think it should be that specific as % per core), same for GPUs and RAM. Maybe include SHM as well if you guys agree.

I think those are the most important ones for reproducibility and track our algorithms and used resources. I like @dbirman idea of instance costs but that'd work only if we register the type of machine that was used. I see it more as another script that based on this info could compute the money we spent.

**Comment by saskiad** [comment]
I think we should hold off on cost in the schema itself. We're making tools to track that - we definitely want eyes on it - but I have reservations about putting it directly into the schema. any thoughts @dyf ?

**Comment by dbirman** [comment]
I'll make a draft with the above, minus cost, and then we can iterate from there.

**Comment by dbirman** [comment]
(blocked waiting on https://github.com/AllenNeuralDynamics/aind-data-schema-models/pull/75)

**Comment by dbirman** [comment]
- [ ] Operating system enum
- [ ] Architecture enum
- [ ] ResourceTimestamp refactor

**Comment by dbirman** [comment]
Waiting on https://github.com/AllenNeuralDynamics/aind-data-schema-models/issues/77
