### ISSUE TITLE
Logging software versions in acquisition?

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#539]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. Instead an inquiry, see below.

**Describe the solution you'd like**
It would be beneficial for SPIM systems (probably all of our systems) to record software information about the given acquisition. For example package versions for imported Python libraries, and for any internal libraries that may be undergoing ongoing development, git hashes. Is this something we already have added into aind-data-schema - or do we think this is worth adding/recording?

**Describe alternatives you've considered**
We currently stores these in the log files for each scan, so it is recorded. This is more of a question about whether we think this is important to push into aind-data-schema.

**Additional context**
None!

**Comment by saskiad** [comment]
We do have a software class in device.py here that is called for specific devices (eg. camera): https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/device.py#L100

Would this work for your purposes or do you need something different?
Do you want to add this to specific devices or for the system as a whole?

**Comment by saskiad** [comment]
@adamkglaser I think this is something we can easily do, but want to get a bit more context of where you'd like us to add software fields. Is it just for the entire system or are there particular devices that are associated with specific software.

**Comment by saskiad** [comment]
Add an optional list of `Software` in the `Acquisition` class.
