### ISSUE TITLE
Support for Navitar and Infinity 

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#550]
At least one of the neuropixels rigs uses both Navitar and Infinity lenses. Navitar and Infinity do not appear to be currently supported by Lens.

**Comment by dyf** [comment]
@mochic these two?
https://www.infinity-usa.com/
https://navitar.com/

**Comment by dyf** [comment]
I see Infinity here: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/406fc35be60789066d6146910bb9f601dae3ba43/src/aind_data_schema/device.py#L205

**Comment by mochic** [comment]
Can we potentially add Navitar as well?
