### ISSUE TITLE
Make stimulus_start_time and stimulus_end_time datetime or duration objects

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#557]
# User story
As a user, I want to record when a stimulus starts and ends as datetime objects or as a single duration object, so I can input correct information.

# Acceptance criteria
- [ ] The time object is for a specific time in a day. If a stimulus happens starts before midnight and ends after midnight, this can cause issues. It's also harder to compare with other datetime objects in the session schema such as session and stream start/end.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by saskiad** [comment]
I'm not sure I agree with this - I do think we want explicit start and end times. I might be missing some context for this issue that's not represented here.

**Comment by jtyoung84** [comment]
Right now, the start and end times are time objects, which are represented like "07:00". It'd be helpful if they were more specific datetime objects like "2023-10-10 07:00" in case the stimulus crosses a day boundary.

**Comment by saskiad** [comment]
They are datetime objects. Oh, wait. I see. In the stimulus class. Yes, those need to be datetimes. I agree.
