### ISSUE TITLE
idea for more readable docs

### ISSUE THREAD

**Issue by tmchartrand** [AllenNeuralDynamics/aind-data-schema#560]
Curious if y'all have considered using https://pypi.org/project/autodoc-pydantic/ to generate more readable schema views?

**Comment by dyf** [comment]
I like this idea.  Will take a look @tmchartrand .

**Comment by jtyoung84** [comment]
@tmchartrand We're gonna track this issue here: https://github.com/AllenNeuralDynamics/aind-data-schema/issues/624
