### ISSUE TITLE
Consider adding alternative information when deprecating previous features

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#565]
**Is your feature request related to a problem? Please describe.**
Some features have a `deprecated` status (e.g. [BehaviorSession](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/behavior/behavior_session.py)). However, no alternative solution is provided.

**Describe the solution you'd like**
I would be great if, when deprecating features, an alternative option is provided. Eg. "This feature has been deprecated in favor of Y feature. For further discussion see issue #XXXX)

**Describe alternatives you've considered**
N/A

**Additional context**
For the sake of the maintainability of the code, a `deprecated` decorator should also be implemented. [See example here.](https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically)

**Comment by saskiad** [comment]
We can add this. 
FYI, the Session class replaces BehaviorSession (and EphysSession and OphysSession)
