### ISSUE TITLE
Consider making `trials_*` properties in `Stimulus` optional

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#578]
Some tasks are simply not trial-based. One could simply leave the trial count at 0, but I believe it would be more inclusive to simply make it an optional field.

**Comment by saskiad** [comment]
Not sure what you are referring to - there is no trials field in Session

**Comment by saskiad** [comment]
do you mean the trials_finished/rewarded etc in the stimulus class?

**Comment by bruno-f-cruz** [comment]
Sorry! Yes, Stimulus class:

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/9967a02777713a02cb07f826d7a6539e9fcf57ef/src/aind_data_schema/stimulus.py#L118

**Comment by saskiad** [comment]
An additional item in this vein, let's move the reward_consumed_total to the session level
and rename reward_consumed_during_training as reward_consumed_during_epoch
