### ISSUE TITLE
Add a `specimen` model

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#58]
Specimen is for keeping track of samples as they are created/subdivided by procedures.

Proposal:
- add a `Specimen` class to `procedures.py`
- and `input_specimen` and `output_specimen` to `Procedure`
- add a `List[Specimen]` to `Procedures`
- add `specimen_id` to `EphysSession`, `Acquisition`, and `OphysSession`.

**Comment by saskiad** [comment]
I think specimen_id only belongs in Acquisition. Ephys and Ophys still use intact subject.

**Comment by saskiad** [comment]
we need the procedure that creates specimens to be different ... not sure which procedure this is

**Comment by saskiad** [comment]
there should be very few procedures that have different input and output specimens...

**Comment by dyf** [comment]
@saskiad Sorry, missed these comments somehow. 

In the past we separated the concept of the Subject from the brain. Right now we are treating those concepts as the same. Not sure how useful it is to separate them, but Specimen could do that.

More important is handling slicing and dissection appropriately, e.g.:
- Removing a section from an exaSPIM brain for spatial transcriptomics
- Slice physiology for patchseq sections

Here the input specimen would be the "brain" (we could just allow `Subject` for this), and the output would be a slice Specimen.  

Other situations I have encountered:
- Perfusion and fixation are procedures that change the brain. We could treat these as separate Specimens. Maybe more headache than it's worth.
- Some experiments extract ROIs from sections for bulk sequencing.  Specimens would be Brain -> Slice(s) -> ROIs.
- Patchseq is a variant of the above: Brain -> Slice(s) -> Cell (for reconstruction). 

The Patchseq example is part of the origin story for the term `cell_specimen` in the past.

**Comment by dyf** [comment]
Summarizing offline conversation:
- Our data assets are for single recordings, therefore
- there will always be a single target specimen, therefore
- we do not have to capture a tree structure - just straight lineage back to the subject.
- This could be represented as 
   1. a list of `Specimen`s, each with a `derivation_procedure`
   2. a list of `SpecimenProcedure`s, each with input and output specimens defined
   3. some complicated graph

I think I personally prefer (1).


>

**Comment by saskiad** [comment]
> @saskiad Sorry, missed these comments somehow.
> 
> In the past we separated the concept of the Subject from the brain. 

We still do. When we remove the brain from the animal, it is a specimen

**Comment by saskiad** [comment]
A specimen is a piece of tissue. If that tissue is sliced, it becomes new pieces of tissue with new specimen IDs. If the tissue is bathed in solution, it is the same piece of tissue.

**Comment by saskiad** [comment]
> * Some experiments extract ROIs from sections for bulk sequencing.  Specimens would be Brain -> Slice(s) -> ROIs.

Specimens are physical things. If we remove a chunk of tissue for sequencing, that's a new specimen. If we trace a cell on a computer image, that is not a specimen.

**Comment by dyf** [comment]
> > * Some experiments extract ROIs from sections for bulk sequencing.  Specimens would be Brain -> Slice(s) -> ROIs.
> 
> Specimens are physical things. If we remove a chunk of tissue for sequencing, that's a new specimen. If we trace a cell on a computer image, that is not a specimen.

Agree.  In my example the ROIs are dissected out.

**Comment by saskiad** [comment]
resolved by PR #170
