### ISSUE TITLE
typo in speaker class in device

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#581]
# User story
As a user, I want the field descriptions correct, so I am not confused

# Acceptance criteria
- [ ] Given a user looks at the field description for Devices, then the correct info will be displayed

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
Go through https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/models/devices.py
and clean up descriptions:
```
class Speaker(Device):
    """Description of a speaker for auditory stimuli"""

    device_type: Literal["Speaker"] = "Speaker"
    manufacturer: Manufacturer.SPEAKER_MANUFACTURERS
    position: Optional[RelativePosition] = Field(None, title="Relative position of the monitor") # Typo
```

### Original issue
relative position of monitor should be relative position of speaker.

Check other instances of RelativePosition (e.g. olfactometer)

**Comment by helen-m-lin** [comment]
This bug fix was very straightforward thanks to @jtyoung84 pointing out exactly which lines needed to be updated. I took some extra time understanding the way that schema versions are updated to ensure PR checks pass.
