### ISSUE TITLE
Validator for device_name of DAQDevices in rig and instrument schema

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#588]
When channels are specified on the DAQDevice, one field is the device_name which needs to point to the name of another existing device in the rig. We need a validator that checks and makes sure the names match.
Josh wrote something like this in the ephys_rig schema that we can probably replicate

**Comment by Sun-flow** [comment]
In attempting this change, it comes to my attention that the majority of our examples do not pass this validation. Adding this validation might be a breaking change for a number of elements. We will need to update the existing examples to be slightly more rigorous, in order for this to push. @saskiad @jtyoung84

**Comment by saskiad** [comment]
my quick look suggests that ephys_rig should be fine with this regard. exaspim_instrument is not because they didn't provide device_names (which should be required imo) . But I can help fix that example. fip_ophys_rig is also a problem, and that we'll need Kenta to fix. 
This is exactly why we need this validator.
