### ISSUE TITLE
add enclosure to rig/instrument

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#594]
include fields for:

- [x] material (enum?)
- [x] size
- [x] grounded = boolean

@jsiegle @adamkglaser What do you think of including this in the rig/instrument schemas? Are there other fields you would want?

**Comment by adamkglaser** [comment]
This is probably more relevant to ephys (seeinfg the grounded field) but not a bad idea for imaging as well. Some other booleans I could see adding would be:

- laser interlock = boolean
- air filtration = boolean

**Comment by jsiegle** [comment]
Good idea, this will be important to track for ephys. There is an external material and an internal material, and size should be 3 dimensions (length, width, height).

There should also be a mandatory `boolean` field for whether an enclosure is present, and then the specific enclosure details should be optional.

**Comment by saskiad** [comment]
I'm going to have the material (internal/external) as a string for now, but I would love to make this a boolean list if possible. If people have examples of materials being used, please share.
