### ISSUE TITLE
remove deprecated ephys/ophys/behavior sessions and rigs

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#601]
These should go away as part of a 1.0 release. 

Remove:
- [ ] `ephys_rig.py` 
- [ ] `ephys_session.py` 
- [ ] `ophys_rig.py` 
- [ ] `ophys_session.py` 
- [ ] `behavior_rig.py`
- [ ] `behavior_session.py`

**Comment by jtyoung84** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-data-schema/pull/608
