### ISSUE TITLE
Improve user documentation

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#602]
**Is your feature request related to a problem? Please describe.**
The schema is difficult to approach as a new user. 

**Describe the solution you'd like**
Improve the sphinx docs to outline major concepts. For example:
- [ ] what is the difference between rig/instrument and acquisition/session?
- [ ] ...

**Comment by jtyoung84** [comment]
Looks like it will be tracked here: https://github.com/AllenNeuralDynamics/aind-data-schema/issues/624
