### ISSUE TITLE
test_behavior uses old schema

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#604]
Update the test to use the pure rig and session schemas

**Comment by saskiad** [comment]
It actually seems like we should remove test_behavior, test_ophys, and test_ephys and make sure that test_rig and test_session cover sufficient use cases

**Comment by jtyoung84** [comment]
I think this has been covered in https://github.com/AllenNeuralDynamics/aind-data-schema/pull/608
