### ISSUE TITLE
Add EMG as Modality

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#612]
should MotorObservatory be a Platform? @dyf

**Comment by Sun-flow** [comment]
@saskiad current format is name + abbreviation for all modality. confirming:

class name: Electromyography
name: electromyography
abbreviation: emg
enum name: EMG

**Comment by saskiad** [comment]
yes that's correct! I'd make the abbreviation `EMG` (all capitals) too.
