### ISSUE TITLE
updates to HarpDevice/DaqDevice

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#632]
- [x] add `firmware` field that uses Software class as optional in DAQ
- [x] add `hardware_version` in DAQ 
- [x] remove harp_device_version in Harp
- [x] Add `harp_device_type_whoAmI` in Harp (id of device type)
- [x] add manufacturers: AIND, Second Order Effects, Champalimaud Foundation (ror=[03g001n57](https://ror.org/03g001n57))
- [x] change `data_interface` to use USB by default, but not to be constant.
- [x] add boolean field `clock_generator`

anything I'm missing @bruno-f-cruz @poofjunior

**Comment by bruno-f-cruz** [comment]
I would change `clock_generator` to `is_clock_generator`.
Also maybe add the field to the harp class `whoAmI`. This is a 4-digit number that fully specifies the device type.

For future reference here's how we are currently defining a device using in harp:

device schema example: https://github.com/harp-tech/device.behavior/blob/main/device.yml 
- The `device`, `whoAmI`, `firmwareVersion`, `hardwareTargets `are probably what we want to track in some of the aforementioned fields

For general harp documentation, here's the new website too:
https://harp-tech.org
and protocol
https://harp-tech.org/protocol/BinaryProtocol-8bit.html

**Comment by saskiad** [comment]
@bruno-f-cruz is whoAmI redundant with `harp_device_type`? Do we really need both if they are redundant?

**Comment by bruno-f-cruz** [comment]
I would rather have the whoami than the name. Makes it way easier to automate code since whoami are guaranteed to be unique and are reserved for each device. I suspect that users will still want the name. So to kill two birds with one stone, I suggest making it an enumerator of int.

**Comment by bruno-f-cruz** [comment]
We do need the whoami and needs to be automatically populated. I can validate devices by whoami (immutable) but not my name (users can change the name of the device). All my workflows validate if the board I am connected to is of the type I expect. 
Also I just thought of a way to automatically instantiate devices that I want to try and this feature would make things so much easier and water tight!
