### ISSUE TITLE
expand schema FAQ

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#639]
https://alleninstitute-my.sharepoint.com/:w:/g/personal/saskiad_alleninstitute_org/EaxGS7r_uslAlzJP2zgWjX4BqNA5vhxTm-v9UbRotY2abg?e=4%3AAD3iv2&fromShare=true&at=9&CID=8f25e924-9daa-bfea-102e-d039d40d79eb

**Comment by mekhlakapoor** [comment]
Incorporate into documentation
