### ISSUE TITLE
add protocol_id to session/acquisition

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#641]
# User story
As a user, I want a protocol_id field in the session and acquisition models, so I can I add the protocol_id to my metadata

# Acceptance criteria
- [ ] Given an engineer looks at the `src/aind_data_schema/core/acquisition.py` file, then they'll see an optional
```
protocol_id: Optional[str] = Field(None, title="Protocol ID", description="DOI for protocols.io")
```
field, when they look in the Acquisition class.
- [ ] Given a user constructs an Acquisition model, then None will be used as a default, when they don't provide a protocol_id
- [ ] Given an engineer looks at the `src/aind_data_schema/core/session.py` file, then they'll see an optional
```
protocol_id: Optional[str] = Field(None, title="Protocol ID", description="DOI for protocols.io")
```
field, when they look in the Session class.
- [ ] Given a user constructs an Session model, then None will be used as a default, when they don't provide a protocol_id
- [ ] Given an engineer runs the test and doc coverage, then the coverage will be 100%, when the coverage report is generated.
- [ ] Given an engineer runs the linters, then no formatting errors will be raised.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Original issue*
```
optional string - just like what we have in procedures.
We already have a SmartSPIM protocol and I think there are some ecephys protocols in the works for the data acquisition stage, so it would be great to record those in these schema.
```

**Comment by jtyoung84** [comment]
@saskiad Do you want the `protocol_id` field to be a required string in the Session and Acquisition classes?

**Comment by saskiad** [comment]
Eventually yes, but not yet
