### ISSUE TITLE
Move definitions of annotated unions?

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#649]
Can we move:
`MOUSE_PLATFORMS = Annotated[Union[tuple(MousePlatform.__subclasses__())], Field(discriminator="device_type")]
STIMULUS_DEVICES = Annotated[Union[Monitor, Olfactometer, RewardDelivery, Speaker], Field(discriminator="device_type")]
RIG_DAQ_DEVICES = Annotated[
    Union[HarpDevice, NeuropixelsBasestation, OpenEphysAcquisitionBoard, DAQDevice], Field(discriminator="device_type")
]
LIGHT_SOURCES = Annotated[Union[Laser, LightEmittingDiode, Lamp], Field(discriminator="device_type")]`

from devices.py to rig.py? 

I think it is much more understandable when this is the same file as the schema itself.

@jtyoung84 is this okay?

**Comment by jtyoung84** [comment]
I think that should be okay. My biggest concern in re-arranging a few of the classes was to avoid potential circular dependencies, but if those are only expected to be imported in rig.py, then it shouldn't be a problem.

**Comment by saskiad** [comment]
I'll take a look a be sure before doing anything. Thanks!

**Comment by saskiad** [comment]
the LIGHT_SOURCES is the only one used in both `rig.py` and `instrument.py`, and we don't want to import across the two. I would either move LIGHT_SOURCES to both of those or leave it here.
The others are unique to rig

**Comment by jtyoung84** [comment]
> the LIGHT_SOURCES is the only one used in both `rig.py` and `instrument.py`, and we don't want to import across the two. I would either move LIGHT_SOURCES to both of those or leave it here. The others are unique to rig

We'll probably want to leave it where it is for now. If it's moved to two different places, it will require maintaining the list in two different places, which can get confusing.
