### ISSUE TITLE
Add flat field correction to ProcessName

### ISSUE THREAD

**Issue by carshadi** [AllenNeuralDynamics/aind-data-schema#664]
We do flat field correction for exaspim data, which consists of background subtraction + shading correction. There is a IMAGE_BACKGROUND_SUBTRACTION type but none for the flat field correction, which is different from destriping.

**Comment by saskiad** [comment]
Isn't flat field correction a `calibration`? There have been a few parallel conversations on this - I'd love to get everyone synced up?

**Comment by saskiad** [comment]
ah, I think you're talking about something else.
