### ISSUE TITLE
Ecephys requires stick microscopes

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#672]
**Describe the bug**
This isn’t really a bug but maybe just a rig difference. Out experiments don’t use stick microscopes. core.rig.Rig validates ephys modalities checking 

**Expected behavior**
Stick microscopes shouldn’t be required for Ecephys modality or some additional check for our type of rig should be performed.

**Desktop (please complete the following information):**
 - Version 0.19.0

**Comment by dyf** [comment]
@jsiegle what do you think about this?

**Comment by jsiegle** [comment]
Having stick microscopes in the rig JSON shouldn't be a requirement. Can the `stick_microscopes` field just be an empty list, or is there some validation step that's preventing that?

**Comment by saskiad** [comment]
there's a validation step that we can easily remove.
