### ISSUE TITLE
Schema Version Check is not reporting branch's schema versions properly

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#688]
**Describe the bug**
The Github actions Schema Version checker does not always properly report the schema version of the branch being merged, if the branch's version is behind main's.

**To Reproduce**
1. Open a PR into main
2. Change some schema version in the modified branch to be earlier than main's schema version
3. Run PR tests
4. See that reported value of "Current Version" and "Old Version" are both the value of main, rather than the value of main and the value of branch.

**Expected behavior**
I would expect one of these values (current or old) to report the existing schema version in branch, even if it is prior to main's version

**Comment by jtyoung84** [comment]
@jtyoung84 Convert this to a user story. Save main branch schemas to a folder and compare those json files to the current ones in a github action

**Comment by jtyoung84** [comment]
We plan to automate the schema version bumps

**Comment by yosefmaru** [comment]
Duplicate
