### ISSUE TITLE
data_description_upgrader cannot handle times which include micro/milli seconds 

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#691]
**Describe the bug**
`data_description_upgrader` does not handle micro/milli seconds, and will throw an overflow error if attempting to upgrade a time that includes them.

**To Reproduce**
1. construct a `DataDescription` model with a time that includes milliseconds or more (format: `"%H:%M:%S.%f"`)
2. attempt to pass that model through `data_description_upgrade.upgrade()`

**Expected behavior**
Date should convert fine, potentially the microseconds should be dropped.

**Screenshots**
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/18150105/e54edf01-7547-4578-9911-be049d31e6b5)

**Comment by dyf** [comment]
Let's move this to [aind-metadata-upgrader](https://github.com/AllenNeuralDynamics/aind-metadata-upgrader).
