### ISSUE TITLE
Allow for different laser controllers for LaserAssembly 

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#707]
For our NP* experiments, the LaserAssembly is controlled via a galvo + DAQ. LaserAssembly requires a manipulator. Maybe LaserAssembly can accept or refer to a DAQ device?

**Comment by saskiad** [comment]
A DAQchannel can connect to a laser in a laser_assembly, do you need something different from that?
Also, are you saying that you don't use a manipulator but instead use a galvo + the DAQ? So we'd want to have a place for the galvo as well?

**Comment by mochic** [comment]
To my understanding that we don't use a manipulator with the lasers but @corbennett might have more insight into this.

**Comment by jtyoung84** [comment]
Duplicated
