### ISSUE TITLE
Consider adding `additional_settings` to `Device` base class

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#708]
**Is your feature request related to a problem? Please describe.**
Having played with the Rig schema lately, I find myself wanting to define device-specific settings so that I can force a specific device state when interacting with the hardware. Currently, the only way to achieve this would be to add this device as a new `Device` class and add the settings as individual properties. While this is a valid approach, it makes it very difficult to quickly prototype different settings that might or might not be relevant in the long run and it also makes the experimenters extremely dependent on the maintenance of the `aind-data-schema`. 

**Describe the solution you'd like**
Similar to the `output_parameters` property in the `BehaviorStimuli`  class:

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/eb4e22a5438eae7c14d83c478b4b8f9233c30422/src/aind_data_schema/models/stimulus.py#L82

I suggest adding a generic property to the `Device` base class named `additional_settings`. This property could still follow the `Dict[str, Any]` pattern or simply `Any` as discussed in #692. It would allow users to pass their own parameters that can be used to instantiate devices, or simply afford a way to annotate some setting that might have otherwise be lost in some sort of generic `notes` field.

**Describe alternatives you've considered**
Add devices and properties as needed. This would make backward compatibility and robust deserialization  nightmare tho...

**Additional context**
N/A

**Comment by saskiad** [comment]
closed by #705
