### ISSUE TITLE
Add support for IMEC headstages

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#721]
We use headstages manufactured by IMEC. Currently the schema only supports Intan headstages.

**Comment by saskiad** [comment]
I propose we remove the `HeadstageModel` enum and rely on the manufacturer and model number in the `Device` class, including both Intan and Imec as manufacturers for Headstages. 
Does this work for you @jsiegle

**Comment by jsiegle** [comment]
Yeah, this is fine!

We didn't originally include the IMEC headstages in that `enum` because there's a 1:1 relationship between Neuropixels probe type and headstage model. But I think it makes more sense to just specify the model via the existing `Device` fields.

**Comment by jtyoung84** [comment]
Duplicated by https://github.com/AllenNeuralDynamics/aind-data-schema/issues/737
