### ISSUE TITLE
Add support for ams-osram and dodotronic manufacturers

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#727]
The manufacturer for our LEDS is ams-osram and the manufacturer for our microphone is dodotronic.

ams-osram
https://www.mouser.com/manufacturer/ams-osram/
dodotronic
https://www.dodotronic.com/

**Comment by saskiad** [comment]
osram: ror_id = [045d0h266](https://ror.org/045d0h266)
name is either osram or ams OSRAM.

No ror_id for dodtronic
