### ISSUE TITLE
Add support for COPA coordinates

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#728]
The relative position class uses x,y,z,pitch,yaw,roll to describe a device's position. Alex Cahoon has created and shared a COPA object position definition format before the winter break which uses:
- Rotation Matrix [3x3] (a-i)​
a,b,c​
d,e,f​
g,h,i​
- Location Matrix [1x3] (xyz)​
x,y,z​

Our rig devices are currently defined in this format. Hopefully changes can be made to the RelativePosition class or a new position class is implemented to support COPA.

**Comment by saskiad** [comment]
Let's discuss options in our meeting tomorrow

**Comment by saskiad** [comment]
do this along with #724
