### ISSUE TITLE
Add a few fields to MRI class

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#757]
in `MRIScan` add:

- [x] `rare_factor` (title= "RARE factor). int
- [x] `vc_orientation` can use `coordinates.Rotation3DTransform`
- [x] `vc_position` can use `coordinates.Translation3DTransform`
- [x] `vc_subject_position` enum prone/supine 
- [x] `resolution`

remove:

- [x] `axes`

I will update as some of these will use classes in the Tile (or coordinates) file. I will detail asap.

**Comment by saskiad** [comment]
##$VisuSubjectPosition=Head_Supine

**Comment by dyf** [comment]
@saskiad combine position/orientation into `List[CoordinateTransformations]` a la the other models?
