### ISSUE TITLE
add targeted ccf coordinates and manipulator coordinates to ephys session example

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#758]

**Comment by micahwoodard** [comment]
What exactly needs to be added? In the session json example , I see targeted_ccf_coordinates and manipulator_coordinates in the EphysModule

`EphysModule(
                    rotation_angle=0,
                    arc_angle=25,
                    module_angle=-22,
                    targeted_ccf_coordinates=[CcfCoords(ml=6637.28, ap=4265.02, dv=10707.35)],
                    ephys_probes=[],
                    assembly_name="ephys module 2",
                    coordinate_transform="behavior/calibration_info_np2_2023_04_24.py",
                    primary_targeted_structure="LC",
                    manipulator_coordinates=Coordinates3d(x=9015, y=7144, z=13262),
                    calibration_date=datetime(year=2023, month=4, day=25, tzinfo=timezone.utc),
                    notes=(
                        "Trouble penetrating. Lots of compression, needed to move probe. Small amount of surface"
                        " bleeding/bruising. Initial Target: X;10070.3\tY:7476.6"
                    )`
