### ISSUE TITLE
Allow spaces in Project name

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#761]
The `project_name` field in `data_description` doesn't allow spaces. We want this to be able to use the project names from the funding smartsheet which do have spaces. Can we change the regex to allow spaces?

**Comment by saskiad** [comment]
is the solution simply to remove the regex for this field entirely or do we make a different regex? I'm not familiar with how to set up regex so I can do the former but not that latter.

**Comment by jtyoung84** [comment]
I would update the regex to just allow spaces

**Comment by micahwoodard** [comment]
@jtyoung84 should I change the NO_SPECIAL_CHARS to allow spaces or create a new enum like NO_SPECIAL_CHARS_EXCEPT_SPACE which allows spaces

**Comment by jtyoung84** [comment]
> @jtyoung84 should I change the NO_SPECIAL_CHARS to allow spaces or create a new enum like NO_SPECIAL_CHARS_EXCEPT_SPACE which allows spaces

We can probably create a new one for this use case
