### ISSUE TITLE
Add stationary platform to device platforms

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#768]
"I am working with a member of MPE to put in instrumentation metadata for the ISI rigs. however, the ISI rigs use a heating pad platform since the mice are sedated but that is not an option in the current schema options." - Hannah Belski

Can we add a stationary platform in list for Mouse Platform.

**Comment by saskiad** [comment]
Can we add this to the ISI issue rather than make a new one please?
