### ISSUE TITLE
Consider enforcing the use of the `default` keyword

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#770]
**Is your feature request related to a problem? Please describe.**
Consider the following example:

```python

from pydantic import Field, BaseModel


class Foo(BaseModel):
    foo_property: int = Field(0)


class Bar(BaseModel):
    bar_property: int = Field(default=0)


foo = Foo()
# Intellisense output: (*, foo_property: int) -> None

bar = Bar()
# Intellisense output: (*, bar_property: int = 0) -> None

```

Without the explicit use of the `default` keyword, intellisense fails to provide the default value of the class. (I am using vscode, not sure if other editors suffer from the same problem). 

**Describe the solution you'd like**
Enforce the use of the `default` keyword to make the lives of people using the schemas easier. Having the default value be provided as part of the IntelliSense string is a really helpful hint! We should also investigate if it is possible to run a check on all models and see if the keyword exists. Could even be part of the unit tests.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by dyf** [comment]
I'm okay with this. @jtyoung84?

**Comment by jtyoung84** [comment]
> I'm okay with this. @jtyoung84?

I'm cool with this also. I'm not sure how to programmatically enforce it without adding the mypy library or something, which might turn into a larger task.

**Comment by bruno-f-cruz** [comment]
Can we please keep using this standard? It makes really difficult to use statically typed libraries if the default keyword is never used. For instance, the `Session` class seems to be a mix between properties with this standard and others without.
