### ISSUE TITLE
Utility method to write out pydantic schemas into json files

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#79]
# User story
As a user, I want to easily export the pydantic models into json, so I can use the json schemas.

# Acceptance criteria
- [ ] There is a utility method that converts the pydantic models to json
- [ ] There is a main method that accepts an optional output dir argument. The main method will write the pydantic models as json files in the output directory (default to current working directory)

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by dana-rocha** [comment]
- utilities directory: __init__py and json_writer.py
- Executable from CLI with an argument that is user defined. This argument is the directory the user wants to write JSON files to. Default to current working directory

**Comment by dana-rocha** [comment]
- CLI arguments (argparse)
- Write out only the classes with AindCoreModel

**Comment by dana-rocha** [comment]
- Loop through the classes in aind-data-schema
