### ISSUE TITLE
Add fields to FieldOfView in Session

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#791]
- [ ] `power`: Optional(Decimal)
- [ ] `power_unit`: percent
- [ ] `scanfield_z` Optional(Decimal? Int?)(@arielleleon can you provide a description for this field? And is it int or decimal?)
- [ ] `scanfield_z_unit`: micrometer
- [ ] `notes`: Optional(str)

@arielleleon did I miss any?

**Comment by arielleleon** [comment]
Thanks - this all looks good. scanfield_z (int) is the z stage position of the fastz actuator for a given targeted depth

**Comment by arielleleon** [comment]
I wanted to make sure that the notes field is to annotate special cases like the back-propagation of rig jsons in the aind-ophys-data bucket for older sessions where the rig may not be in the same configuration.

**Comment by saskiad** [comment]
I wouldn't use the notes for the FOV class to annotate that - I think that would be in the main session notes or maybe the rig.json actually. But I think it's good to have notes fields in case there are things that come up that we can't capture that we need to include for some off-case uses.
