### ISSUE TITLE
Immersion Medium string field

### ISSUE THREAD

**Issue by miketaormina** [AllenNeuralDynamics/aind-data-schema#815]
**Is your feature request related to a problem? Please describe.**
Enumerated 1ImmersionMedium` types do not capture EasyIndex or Ethyl Cinnimate, two commonly used SmartSPIM reagents.

**Describe the solution you'd like**
Since there will likely always be new and weird things people want to try for sample immersion, these would be enumerated as "Other" and the acquisition `Immersion` class would have a new (optional field) titled `description`, in which EasyIndex, Ethyl Cinnimate, Cargille oil, etc. can be placed.

**Describe alternatives you've considered**
Expanding the enumerated list of mediums

**Additional context**
I think this also makes the existing fields more useful, since `OIL` can have the description `Cargille (product number)`, `PBS` can specify concentration, etc.

**Comment by saskiad** [comment]
I thought we had landed on expanding the enum. I'm not keen on adding a description field here.
