### ISSUE TITLE
Add NResearch and Hamilton organizations

### ISSUE THREAD

**Issue by mochic** [AllenNeuralDynamics/aind-data-schema#819]
The manufacturer for the syringe used in our reward delivery system is [Hamilton](https://www.hamiltoncompany.com/laboratory-products/needles?utm_source=adwords&utm_term=syringes%20for%20sale%20online&utm_campaign=Syringe+and+Needle&utm_medium=ppc&hsa_tgt=kwd-342095680941&hsa_src=g&hsa_cam=1378653494&hsa_grp=57603372151&hsa_acc=3619911770&hsa_ver=3&hsa_ad=389439025664&hsa_net=adwords&hsa_kw=syringes%20for%20sale%20online&hsa_mt=p&gad_source=1&gclid=CjwKCAiAi6uvBhADEiwAWiyRdjmFHwESdImI5i7Qv3WXdYfH0x6tKDaYfPKLReEAhbhzuVH6QTT6OBoCpxgQAvD_BwE)

The manufacturer for the solenoid used in our reward delivery system is [NResearch](https://www.globalspec.com/supplier/profile/NResearch)

We would like to have these organizations added so that we can use them as manufacturers in our neuropixels rig schema.

**Comment by saskiad** [comment]
neither has a ror id
