### ISSUE TITLE
Bug: date times are wrong by default

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/aind-data-schema#832]
I just noticed that a recording session.json made with this library, using a time zone naïve datetime, has the wrong date time in the JSON file. This is from a recording "661277_2023-05-11_19-37-50," which happened at 2023-05-11T19:37:50-07:00 (America/Los_Angeles). However, the JSON records the session start time as "2023-05-11T19:37:50+00:00," which is wrong as it shows the same "local time" but the wrong time zone (+00:00 instead of -07:00) meaning the UTC date time is incorrect. Because it has the (wrong) time zone attached, people would probably not interpret it as a naïve date time.

I would suspect this bug affects many metadata files generated with this library if they were generated using naïve date times, which no doubt are what many people use.

Attached example file:
[ephys_session.json](https://github.com/AllenNeuralDynamics/aind-data-schema/files/14590828/ephys_session.json)

**Comment by jtyoung84** [comment]
We added timezone aware time string handling. We may need to go back and clean up the old json files.
