### ISSUE TITLE
Validation Errors when InjectionMaterials is combination of models

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-schema#842]
**Describe the bug**
When injection_materials contains both ViralMaterial and NonViralMaterial objects, the injection fails validation due to "extra input" and "field required" errors. It is incorrectly validating ViralMaterial objects against NonViralMaterials and vice versa.

**To Reproduce**
1. Create a ViralMaterial with some fields (ex: titer)
2. Create a NonViralMaterial with some fields (ex: concentration)
3. Create an Injection with injection_materials = [viral, nonviral]
```
from aind_data_schema.core.procedures import TarsVirusIdentifiers, NanojectInjection, ViralMaterial, NonViralMaterial
ids = TarsVirusIdentifiers.model_construct(virus_tars_id="AiV123", prep_lot_number="lot123")
viral = ViralMaterial.model_construct(name="example", tars_identifiers=ids, titer=7000000)
non_viral = NonViralMaterial.model_construct(concentration=0.5)
inj = NanojectInjection.model_construct(injection_materials=[viral,non_viral]
 inj.__class__.model_validate(inj.model_dump())
```
4. See validation errors.

<img width="945" alt="Screen Shot 2024-03-15 at 1 31 42 PM" src="https://github.com/AllenNeuralDynamics/aind-data-schema/assets/54870020/3c258013-edcb-4dca-9ab5-1e2f45fe2504">

**Expected behavior**
injection_materials is a union of ViralMaterial and NonViralMaterial. It should allow and validate correctly. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bruno-f-cruz** [comment]
You are forcing the model to be built without validation by calling the `model_construct` model (see the relevant documentation here)[https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_construct].

The trace you get is not from the final NanojectInjection per se but instead because of the recursive validation of the ` `NonViralMaterial`.  Here's a working example that should get you started:

```python
from aind_data_schema.core.procedures import TarsVirusIdentifiers, NanojectInjection, ViralMaterial, NonViralMaterial
from aind_data_schema.models.organizations import Organization

ids = TarsVirusIdentifiers(virus_tars_id="AiV123", prep_lot_number="lot123")
viral = ViralMaterial(name="example", tars_identifiers=ids, titer=7000000)
non_viral = NonViralMaterial(name="example", source=Organization.ABCAM, rrid=None, lot_number="foo", expiration_date=None)
inj = NanojectInjection(injection_materials=[viral, non_viral],
                        injection_coordinate_ml=0, injection_coordinate_ap=0, injection_coordinate_depth=[0, +10, -10],
                        protocol_id="bar", injection_angle=0, injection_volume=[-10, 0, 0])
inj.model_validate(inj.model_dump())
```

**Comment by jtyoung84** [comment]
This signature is incorrect and may fix the bug if we fix it:

```python
injection_materials: Annotated[
        List[Union[ViralMaterial, NonViralMaterial]],
        Field(title="Injection material", min_length=1, discriminator="material_type"),
    ]
```

**Comment by micahwoodard** [comment]
I think  this bug might have already been fixed? I can't reproduce the bug when using Bruno's example and injection_materials already has the [signature](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/661a49b011a6f61cbc79e61245308b1c39322103/src/aind_data_schema/core/procedures.py#L378C5-L381C6) Jon suggested. Let me know if I'm missing something!

**Comment by mekhlakapoor** [comment]
Closing this issue because it works with Bruno's example. Opening [issue](https://github.com/AllenNeuralDynamics/aind-metadata-service/issues/211) in metadata-service to fix construction of models to not use model_construct
