### ISSUE TITLE
Consider adding property to `Calibration` to afford discriminated unions in inherited models

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-schema#846]
**Is your feature request related to a problem? Please describe.**
Looking at the current `Calibration` model there isn't a suitable property that can be leveraged to create discriminated unions (e.g. a string)
https://github.com/AllenNeuralDynamics/aind-data-schema/blob/0328cbed69d5da849660557be162a24c2cd02df4/src/aind_data_schema/models/devices.py#L271

This is unfortunate as Calibration is already being used for `List` types, for instance in https://github.com/AllenNeuralDynamics/aind-data-schema/blob/0328cbed69d5da849660557be162a24c2cd02df4/src/aind_data_schema/core/acquisition.py#L58

**Describe the solution you'd like**
It would be ideal to add an extra property to the `Calibration` class that specifies the type of the calibration being spec'ed. This would allow correct deserialization should users subclass `Calibration` whilst leaving deserialization in the aind-data-schemas untouched.

This is all the more problematic since, currently, the base class (`AindModel`) operates in `forbid` mode which completely removes the ability of users that want to inherit from the base class to add such a discriminated property and still honor the deserialization to the aind-data-schema spec.

**Describe alternatives you've considered**
Change the deserialization mode from `forbid` to `ignore`

**Comment by bruno-f-cruz** [comment]
Another possibility is to hack the `description` field to do this. I don't think this is a good idea but it will make it backward compatible.

**Comment by bruno-f-cruz** [comment]
Related to #855 #850

**Comment by saskiad** [comment]
It seems that between the `device_name` and `description` we should be able to discrimate these, no?

**Comment by bruno-f-cruz** [comment]
I ended up fixing this on my end differently. I think it's ok since the aind-data-schemas is not concerned with deserializing the children of Calibration to their correct subtype. Instead, it will always deserialize to the Calibration base class.

Closing this issue. Thanks!
