### ISSUE TITLE
add additional devices to imaging schema

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#86]
Motorized stage and DAQ are currently not exposed in a class. However they are a common item across SPIM systems and could be added as a dedicated class.

Suggested addition(s) to [instrument.py](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/imaging/instrument.py)
````python
class MotorizedStage(Device):
    """Description of a motorized stage device"""

    manufacturer: str = Field(..., title="Manufacturer of device")  
    model: str = Field(..., title="Model of device")  
    axes: str = Field(..., title="Axes of device")
    travel: float = Field(..., title="Travel of device (mm)")

class DAQ(Device):
    """Description of a DAQ device"""

    manufacturer: str = Field(..., title="Manufacturer of device")  
    model: str = Field(..., title="Model of device")
    device_name: int = Field(..., title="PC device name")
    update_frequency: int = Field(..., title="Update frequency [hz]")
````

An alternative is to add them as an ````AdditionalImageDevice````. Although since they are common to all systems, I think this is not the best solution?

**Comment by saskiad** [comment]
is it possible there will be multiple daq or motorizedstages for a given microscope? I believe no, but just want to make sure

**Comment by saskiad** [comment]
"axes" refers to the axis that the motorized stage travels in? I'm wondering if we can use the Direction class in the acquisition schema here. Thoughts @dyf?

**Comment by adamkglaser** [comment]
> is it possible there will be multiple daq or motorizedstages for a given microscope? I believe no, but just want to make sure

That is right, there would only be a single DAQ. For motorized stages, we could either bundle all of the axes into a single stage/device. Or separate them out into individual axes. The latter might make more sense since the travel would be different for all of them. Which if they were combined, would require travel to be an array.

**Comment by saskiad** [comment]
I'm good making an array of stages - that's easy to do.

I'm concerned about the axes. How are we defining it? If it's relative to anatomy, that only makes sense in the context of an acquisition session where there is tissue. If it's relative to geometrical space, we need to figure out what that is in this schema.

**Comment by adamkglaser** [comment]
The axes are confusing. I think the different permutations to choose from are.

1. Purely based on the hardware driver/devices. The stages from the manufacturer ASI all get assigned a lettered axis in the firmware. This is somewhat arbitrary though, and vary depending on how a specific instrument is assembled. This probably isn't a good option.
2. Based on the light-sheet general architecture. There will always be an axis which is parallel to the imaging objective. One parallel to the light-sheet generating objective. And then the third axis which is perpendicular to both of the previous ones. This might be the best option within the instrument class?
3. Finally anatomical axes. This depends on how we mount the tissue relative to the above. It seems like if we adopt 2 for the instrument, then we map from 2 -> 3 based on a given acquisition session.

Does this sound like a good plan?

**Comment by saskiad** [comment]
I'm good with using 2 - but I guess the question is how do we describe the axes here. Does it make sense to use the language you have here? "Parallel to imaging objective" "Parallel to light-sheet generating objective" and "Perpendicular to both objectives" ? Is there better language?

**Comment by adamkglaser** [comment]
Ack that is too verbose. I think we could shorten as "along detection axis", "along illumination axis", and "along perpendicular axis". Or make the assumption that we are specifying along/parallel, and further simplify to "detection axis", "illumination axis", "perpendicular axis"

**Comment by saskiad** [comment]
@adamkglaser we have a daq_ao_names_to_channel item in the schema - should that live in the DAQ class? or outside of it?
