### ISSUE TITLE
Add software to data stream/session

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#861]
We need a way to document the software used in data collection. Eg. OpenEphys, sync, etc. Stimulus control software is already in the StimulusEpoch class and software for specific devices (e.g. cameras) are in those devices. But we need to document recording software.
Probably it belongs in `Stream` but could also be in the `Session` class. It should be a list.

**Comment by dyf** [comment]
I think `Stream` makes more sense than `Session`.

**Comment by dyf** [comment]
Should be a list, can be optional.

**Comment by mekhlakapoor** [comment]
closing this issue as completed
