### ISSUE TITLE
Modify specification of optical table size in imaging schema

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#87]
Expand optical table dimension specification to tables with different width/lengths.

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/e9e85c5732c3ec80779c9131fca531b72f84aaf6/src/aind_data_schema/imaging/instrument.py#L182-L183

Change spec from ````optical_table_size```` to ````optical_table_length```` and ````optical_table_width````.

Another option is to change ````optical_table_size```` to an array.

**Comment by saskiad** [comment]
@adamkglaser what units do you specify table sizes in? meters? feet?

**Comment by adamkglaser** [comment]
Sorry missed your response. For better or worse, the tables are usually specified in inches.
