### ISSUE TITLE
add behavior rig template to the example folder

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/aind-data-schema#872]
It would be great if you could add the following rig template for the foraging behavior team to the `example` folder and maintain for version updates.
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/develop/src/setting_templates/447_FIPBehaviorOpt_FullModalityTemplate.py

**Comment by saskiad** [comment]
this is blocked by Pydantic version issue
