### ISSUE TITLE
Schema warnings related to Unions

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema#875]
**Describe the bug**
All of the test runs show something like this:
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/1854389/d52263e1-a7f0-4ade-8e8d-db54ca9a4382)

**Expected behavior**
These should not appear.

**Comment by mekhlakapoor** [comment]
Warnings also occur for Surgery: Expected `Union[Surgery, TrainingProtocol, WaterRestriction, definition-ref]` but got `Surgery` - serialized value may not be as expected

**Comment by mekhlakapoor** [comment]
Closing this issue as the warnings are harmless and seems to be a bug in pydantic-core. 
Monitor these issues: 
- https://github.com/pydantic/pydantic/issues/8756
- https://github.com/pydantic/pydantic/issues/7905
