### ISSUE TITLE
add filter position to filter spec class

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/aind-data-schema#88]
````Lightsource```` class currently specifies matching filter by #. But this field does not also map over into the ````Filter```` class. So the filter position # cannot be linked the the actual filter specs.

Suggest added the same ````filter_wheel_index```` into the Filter class.

````python
class Filter(Device):
    """Description of a filter device"""

    type: FilterType = Field(..., title="Filter Type")
    diameter: float = Field(..., title="Size (mm)", ge=0)
    thickness: float = Field(..., title="Size (mm)", ge=0)
    filter_wheel_index: int = Field(..., title="Filter index")
    description: Optional[str] = Field(
        None, description="Where/how filter is being used", title="Description"
    )
````

Alternatives. Does it make sense to duplicate this same parameter into both classes? Or perhaps move the filter_wheel_index out of the ````Lightsource```` class and only into the ````Filter```` class.

**Comment by saskiad** [comment]
I guess I don't really know what the filter_wheel_index really means. I'm fine with moving it to filter. I take it that duplicating doesn't make sense?

**Comment by saskiad** [comment]
are there any filters that aren't in a filter wheel?

**Comment by dyf** [comment]
I think @adamkglaser is saying that he wants to associate a `Lightsource` with a `Filter`.  You could do that by having a common index between the two, or just moving the entire `Filter` description to `Lightsource`.  e.g.:

```
class Lightsource(Device):
   filter: Filter
```

Is that right @adamkglaser ?

**Comment by dyf** [comment]
A `Filter` has a position on a filter wheel, and there is one filter wheel per `Lightsource` -- is this right?

If so, `filter_wheel_index` doesn't make sense on the `Lightsource` and should move to `Filter`.

**Comment by saskiad** [comment]
perfect, I'll do this. And add a lightsource - filter item in the acquisition schema

**Comment by adamkglaser** [comment]
great, once this and #87 and #86 are modified i will finalize and send over the schema
