### ISSUE TITLE
Add software field to session

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#881]
We want to indicate what software is being used in data acqusition. We should add this to the `DataStream`. 
We probably want to remove `Software` from the device classes (`Detector` and `Disc` come to mind) but we will want to specify which part of the data stream the software is for. So perhaps we add a class that specifies the Software and which devices it applies to. e.g. OpenEphys will apply to all the ephys_modules. Whereas it's conceivable (though unlikely) that different cameras might use different software to record them.

**Comment by saskiad** [comment]
Duplicate of #861

**Comment by dyf** [comment]
closing, dupe
