### ISSUE TITLE
Upgrade to pydantic 2.7

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#888]
**Is your feature request related to a problem? Please describe.**
There are a lot of new features added to 2.7. We should consider putting it as a lower bound:
https://blog.pydantic.dev/blog/2024/04/11/2-7-release/

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bruno-f-cruz** [comment]
Is there an ETA for this update? I am a bit blocked on my until this happens. 

Specifically, the [curriculum](https://github.com/AllenNeuralDynamics/aind-behavior-curriculum) is not compatible with this requirement.

**Comment by dyf** [comment]
@jtyoung84 we can do this, but we need to make sure that the JSONschemas published to S3 are still using <2.6.
