### ISSUE TITLE
Laser Assembly additions

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#893]
- [ ] Add a field for `collimator` that uses the `Devices` class
- [ ] Add a field for `fiber` that uses the `Patch` class
- [ ] both should be required. This makes this a minor change (rather than a patch)

**Comment by Sun-flow** [comment]
What schema should be receiving this minor bump?

**Comment by Sun-flow** [comment]
bump for `rig.py`, perhaps instrument due to inheriting devices.
