### ISSUE TITLE
add exaspim source orgs

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema#902]
Need to add orgs:

SICGEN: Name: SICGEN
ABR: none
RORID: none 

Invitrogen: <-- this seems like a subsidy/child/sister of Thermo Fisher -- we could maybe relate them somehow
Name: Invitrogen
ABR: none
RORID: Use RORID for Thermo Fisher

**Comment by saskiad** [comment]
Let's wait until Jon's reorg of enums is finished.
