### ISSUE TITLE
Inconsistent names of LED device_type

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/aind-data-schema#923]
**Describe the bug**
The `device_type` of `LightEmittingDiodeConfig` is `LightEmittingDiode` (in the `session.py`).
 ![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/26fb42f4-1d80-453b-bc8c-8b3e7a9ad1ab)

The `device_type` of `LightEmittingDiode` is `Light emitting diode` (in the `devices.py`).
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/0c9e8d9f-ba97-496a-b1af-f239ab92e0a6)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saskiad** [comment]
Let's remove camel case from all device_type names
