### ISSUE TITLE
format of session.py/StimulusEpoch/light_source_config

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/aind-data-schema#925]
**Describe the bug**
`session.py/StimulusEpoch/light_source_config` only permits configuring one light source. However, sometimes we have multiple light sources associated with one `StimulusEpoch`, so it's better to change the `light_source_config` to `List` instead of using `dictionary`. 

Current: 
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/db190dc4-afcd-4d3b-b7ce-053f3f4ddefb)
Suggested changes:
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/d8e502d4-4917-4820-9017-e7b129cd269f)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by XX-Yin** [comment]
@saskiad I submitted a new issue. Please take a look. Maybe I misunderstood it.

**Comment by saskiad** [comment]
I believe the LIGHT_SOURCE_CONFIG functions as a list. 
`LIGHT_SOURCE_CONFIGS = Annotated[
    Union[LightEmittingDiodeConfig, LaserConfig],
    Field(discriminator="device_type"),
]`
You should be able to have multiple LaserConfig instances there.

**Comment by XX-Yin** [comment]
@saskiad 
The error information is showed below. If I changed the `light_source_config` to `List` type (`light_source_config: Optional[List[LIGHT_SOURCE_CONFIGS]] = Field(None, title="Light source config")`), the error was fixed. 

I think `LIGHT_SOURCE_CONFIGS = Annotated[ Union[LightEmittingDiodeConfig, LaserConfig], Field(discriminator="device_type"), ]` means the `LIGHT_SOURCE_CONFIGS ` should have the same format as `LightEmittingDiodeConfig` or `LaserConfig`, and it doesn't mean `LIGHT_SOURCE_CONFIGS ` should be a `List`.
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/0b259052-8df6-41c2-8295-b70a2409d76e)

**Comment by XX-Yin** [comment]
@saskiad I am happy to reproduce this issue if you could stop by my desk.

**Comment by XX-Yin** [comment]
@saskiad I understand that you are busy and have other stuff to address. It takes only 5m to reproduce the error if you can stop at my desk 330A-04.

**Comment by saskiad** [comment]
@XX-Yin did you get this figured out from the example?

**Comment by XX-Yin** [comment]
No! Do you have a moment to stop by my desk 330A-04?

**Comment by XX-Yin** [comment]
Let me know when you plan to come
