### ISSUE TITLE
adding reference_manipulator_coordinates and target_manipulator_coordinates

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/aind-data-schema#926]
**Is your feature request related to a problem? Please describe.**
We usually have two manipulator coordinates corresponding to the target and reference coordinates during the experiment. It's meaningless to have manipulator coordinates without providing the reference manipulator coordinates. Currently, we only have the `manipulator_coordinates` in the `session.py/ManipulatorModule`.
**Describe the solution you'd like**
Current
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/59f0b843-91a8-409f-84fd-1a914beea0eb)

Suggested
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/75c5e68f-0e87-4895-95a8-9383910bed03)

**Describe alternatives you've considered**

**Additional context**

**Comment by XX-Yin** [comment]
Keep @KanghoonJ  updated.

**Comment by XX-Yin** [comment]
The background is I am creating the ephys module as shown below. There is one field related to the manipulator (used to hold the probe) coordinates. We currently only have one coordinate in the `manipulator_coordinates`, which is meaningless if there are no reference coordinates. 
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/7ecbd3b7-6efa-49cb-8fec-b3b0ce31b755)

It's not from the `DomeModule`. The angles highlighted below are used to define angles of the probe or stick microscopy. We also need the manipulator coordinates during ephys experiment. One coordinate is the reference coordinate (e.g the brain surface), and the other coordinate is the target coordinate.  


![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/3da4aa85-f193-468c-961b-1325561774a7)

**Comment by saskiad** [comment]
I think this was addressed by #932 - can you confirm that this meets your needs?

**Comment by XX-Yin** [comment]
It was partially addressed by `add surface_z to ManipulatorModule as an optional Decimal.` 

I think it's more flexible to add optional `reference_manipulator_coordinates` and `manipulator_reference_area` instead of one `surface_z ` as the reference area may be changed (e.g., bregma).

**Comment by saskiad** [comment]
My proposal is to rename `bregma_coordinates` with `anatomical_coordinates` and then add a field of `anatomical_reference` where the options are bregma, lambda, other. 
Does that work? And @jsiegle: does this work for you?

**Comment by XX-Yin** [comment]
What is the relationship between `bregma_coordinates (or anatomical_coordinates)` and `reference_manipulator_coordinates`?

**Comment by saskiad** [comment]
we added `bregma_coordinates` to provide coordinates relative to a reference point. It sounds like you want this to be flexible in terms of what the reference point is. My suggestion is to rename this `anatomical_coodinates` and add a field for what the reference is.

**Comment by XX-Yin** [comment]
"My suggestion is to rename this anatomical_coodinates and add a field for what the reference is." Sounds good!

**Comment by saskiad** [comment]
@jsiegle does this work for your team?

**Comment by XX-Yin** [comment]
To be clear, do you want to rename the `anatomical_coodinates` to `reference_manipulator_coordinates` and add a field called `reference_manipulator_area`? 
Also, where does the `target_manipulator_coordinates` should go?

**Comment by saskiad** [comment]
No. I want to rename the `bregma_coordinates` to `anatomical_coordinates`. I think the name `reference_manipulator_coordinates` is unclear and will cause confusion. The `anatomical_reference` then specifies what the anatomical coordinates are in reference to (either Bregma or Lambda). This is what you are asking for, is it not?

**Comment by XX-Yin** [comment]
`anatomical_coordinates` and `anatomical_reference` work for me. However, I am not clear how do you differentiate `target coordinates` and `reference coordinates`? We have two coordinates for manipulator (target coordinates and reference coordinates).

**Comment by saskiad** [comment]
What are the reference coordinates?

**Comment by XX-Yin** [comment]
Never mind. I got what you mean now. It's ok to only have `anatomical_coordinates` and `anatomical_reference`, but we should keep `anatomical_reference` flexible (not limited to bregma and lambda).

**Comment by jsiegle** [comment]
I think this change sounds good!

**Comment by XX-Yin** [comment]
> What other references do you want to include other than bregma and lambda?

In ephys recordings, it is more commonly the brain surface (we hope to know how deep the probe goes into the brain) rather than the bregma and lambda.

**Comment by XX-Yin** [comment]
If you want to keep items in `anatomical_reference` fixed, then adding `brain surface` to it should also work.

**Comment by saskiad** [comment]
isn't this `surface_z`?

**Comment by KanghoonJ** [comment]
For additional /anatomical_reference, adding  
/midline would be informative.

**Comment by KanghoonJ** [comment]
I understand. In my current recording setup, the precise AP coordinate value for the probe insertion spot is often not available. However, I can record the 'midline' coordinate by adding the ML value for the 'bregma' coordinates as the 'anatomical_reference'. Therefore, there’s no need to add a separate 'midline' field.

**Comment by XX-Yin** [comment]
> isn't this `surface_z`?

What is `surface_z`? It's a coordinate or a reference area?

**Comment by saskiad** [comment]
it's the coordinate depth (z) at the surface of the brain.

**Comment by XX-Yin** [comment]
When we talk about coordinate, it should have a reference. What is the reference of `surface_z`?

**Comment by saskiad** [comment]
It is the depth of the manipulator at the surface of the brain. It thus provides the depth reference for the final probe position.

**Comment by XX-Yin** [comment]
After talking with @saskiad in person, we agree to add three fields `anatomical_coordinates`, `anatomical_reference` and `surface_z`. The `anatomical_coordinates` is used as the intended target coordinates referring to `anatomical_reference`. The `surface_z` is how deep the probe is in the brain along the insertion `z` direction.
