### ISSUE TITLE
Missing important connections 

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/aind-data-schema#927]
**Is your feature request related to a problem? Please describe.**

Laser/LED can be connected to patch cables, and the patch cable can be connected to fibers. 
It seems that fields to link them in the `devices.py/Laser`,  `devices.py/LightEmittingDiode` and `devices.py/Patch` are missing. And I also found there is no independent Fiber device in the `rig.py/Rig`. There is `fiber_assemblies` that is more related to fibers held by the manipulator.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by XX-Yin** [comment]
@saskiad @dyf @jsiegle @galenlynch @alakunina @hanhou 

There is a more general question how to easily define connections between devices.  Currently, we can define devices in rig metadata, but important connection information between those devices is missing for some devices. One solution is to add additional connection and connector fields for all devices, and then we can link them.

**Comment by saskiad** [comment]
I'm going to close this as an issue while we discuss #929
