### ISSUE TITLE
New fields to define the wavelength of Lamp

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/aind-data-schema#928]
**Is your feature request related to a problem? Please describe.**
The `wavelength` of `Lamp` is currently defined by `wavelength_min` and `wavelength_max`, I think this design is for light with adjustable wavelength. In some cases, the wavelength is a normal distribution (one example shown below), and it's meaningless to define `wavelength_min` and `wavelength_max` here. Instead, we can define the `wavelength` by `nominal wavelength` and the `distribution` by `FWHM`. 

![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/36dc5467-6923-4cb1-8f75-022d68f3ae1b)
![image](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/109394934/b87c95af-dc13-4a0c-b062-2baa117d4188)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by XX-Yin** [comment]
@saskiad @Sun-flow Please take a look. Thanks

**Comment by saskiad** [comment]
@XX-Yin the example you show above is a LED which should use the `LightEmittingDiode` class which does have a `wavelength` field. Would you like me to add the bandwidth field to that class?

**Comment by XX-Yin** [comment]
> @XX-Yin the example you show above is a LED which should use the `LightEmittingDiode` class which does have a `wavelength` field. Would you like me to add the bandwidth field to that class?

@saskiad Yes, the example is an IR LED used for illumination of cameras. Do you suggest that I add it to the `LightEmittingDiode` instead of the `Lamp`? My understanding is the `LightEmittingDiode` or `Laser` is more for focused illumination and the `Lamp` is for general illumination of the environment. Here, the illumination for cameras is more like the general environment illumination. 

Yes, I think the bandwidth (FWHM) is useful for LED.

**Comment by saskiad** [comment]
Yeah, I suggest you use the LED and you can specify in the `Notes` how you are using it (eg. "illumination for eye tracking").

And we can add the bandwidth to the class.
