### ISSUE TITLE
ephys updates

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema#932]
- [ ] in `session.py` remove `EphysProbeConfig` and `EphysModule`. Add `other_targeted_structures` field to `ManipulatorModule` as an optional list (see how it currently is in EphysProbeConfig)
- [ ] in `session.py` in `Stream` change ephys_modules to be `ephys_modules: List[ManipulatorModule] ...`
- [ ] add `bregma_coordinates` to `ManipulatorModule`. Make this optional, use `Coordinates3d`
- [ ] add `surface_z` to `ManipulatorModule` as an optional Decimal. @jsiegle what should the unit for this be?
- [ ] add `dye` to `ManipulatorModule` as an optional string
- [ ] add `headframe_registration` to `Session`. This is optional. Use `Affine3Dtransform` which needs to be imported from Coordinates. description is "MRI transform matrix for headframe"

@jsiegle did I miss anything from our SLIMS meeting last week?

**Comment by saskiad** [comment]
this will be a minor version bump

**Comment by jsiegle** [comment]
These look good! `surface_z` units should be the same as `Coordinates3d`, which is `SizeUnit.UM`
