### ISSUE TITLE
Add MetadataStatus per core schema in Metadata pydantic model

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema#934]
**Is your feature request related to a problem? Please describe.**
It would be nice to get a top level check of the status of each of the core schemas attached to a data asset (subject, procedures, rig, etc.) Some of the flags could be:

**Describe the solution you'd like**
It would be nice to get a top level check of the status of each of the core schemas attached to a data asset (subject, procedures, rig, etc.). For example, we could `subject_status`, `rig_status`, etc. to the Metadata model. Some of the flags could be:

```
Valid: There is a valid model
Invalid: There is an invalid model
Corrupt: There is a json file found with the data asset, but it's not possible to add the json file to DocDB for some reason
Missing: There is no json file found for this data asset (this may be redundant if we just the field to None)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by dbirman** [comment]
After discussion w/ Saskia we've agreed to validate and store the state outside of the metadata itself. We're working on the validator code here: https://github.com/AllenNeuralDynamics/aind-metadata-validator/ and it will push to a redshift db (or somewhere else) and then we can use aind-data-access-api to expose the database.

**Comment by jtyoung84** [comment]
Sounds good, I'll close this issue out then.
